package uk.gov.cca.api.workflow.request.flow.performancedata.common.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TP6ExcelCellsReferenceEnum {

    // Section 1: Report Details
    SECTOR(4, 2),
    TARGET_PERIOD(5, 2),
    REPORT_VERSION(6, 2),
    TEMPLATE_VERSION(7, 2),
    REPORT_DATE(8, 2),

    // Section 2: Target Unit Details, Targets and Previous Performance
    TU_IDENTIFIER(15, 4),
    OPERATOR_NAME(16, 4),
    NUM_OF_FACILITIES(17, 4),
    TARGET_TYPE(18, 4),
    ENERGY_CARBON_UNIT(19, 4),
    THROUGHPUT_UNIT(20, 4),
    BASE_YEAR_START_DATE(21, 4),
    BASE_YEAR_ENERGY(22, 4),
    BASE_YEAR_THROUGHPUT(23, 4),
    BASE_YEAR_PERFORMANCE(24, 4),
    NUMERICAL_TARGET(25, 4),
    TOLERANCE(26, 4),
    PERCENT_IMPROVEMENT_TARGET(27, 4),
    TOLERANCE_PERCENTAGE(28, 4),
    BANKED_SURPLUS_FROM_PREVIOUS_TP(30, 4),

    // Section 3: Actual Target Period Performance for Target Facility
    ACTUAL_TU_IDENTIFIER(36, 5),
    ACTUAL_THROUGHPUT(37, 5),
    ELECTRICITY_USED(38, 5),
    NATURAL_GAS_USED(39, 5),
    FUEL_OIL_USED(40, 5),
    COAL_USED(41, 5),
    COKE_USED(42, 5),
    LPG_USED(43, 5),
    ETHANE_USED(44, 5),
    KEROSENE_USED(45, 5),
    PETROL_USED(46, 5),
    GAS_DIESEL_OIL_USED(47, 5),
    NAPHTHA_USED(48, 5),
    PETROLEUM_COKE_USED(49, 5),
    REFINERY_GAS_USED(50, 5),


    OTHER_FUEL_USED_1_CONSUMPTION(51, 5),
    OTHER_FUEL_USED_1_NAME(51, 2),
    OTHER_FUEL_USED_1_CONVERSION_FACTOR(51, 3),

    OTHER_FUEL_USED_2_CONSUMPTION(52, 5),
    OTHER_FUEL_USED_2_NAME(52, 2),
    OTHER_FUEL_USED_2_CONVERSION_FACTOR(52, 3),

    OTHER_FUEL_USED_3_CONSUMPTION(53, 5),
    OTHER_FUEL_USED_3_NAME(53, 2),
    OTHER_FUEL_USED_3_CONVERSION_FACTOR(53, 3),

    OTHER_FUEL_USED_4_CONSUMPTION(54, 5),
    OTHER_FUEL_USED_4_NAME(54, 2),
    OTHER_FUEL_USED_4_CONVERSION_FACTOR(54, 3),

    OTHER_FUEL_USED_5_CONSUMPTION(55, 5),
    OTHER_FUEL_USED_5_NAME(55, 2),
    OTHER_FUEL_USED_5_CONVERSION_FACTOR(55, 3),

    OTHER_FUEL_USED_6_CONSUMPTION(56, 5),
    OTHER_FUEL_USED_6_NAME(56, 2),
    OTHER_FUEL_USED_6_CONVERSION_FACTOR(56, 3),

    OTHER_FUEL_USED_7_CONSUMPTION(57, 5),
    OTHER_FUEL_USED_7_NAME(57, 2),
    OTHER_FUEL_USED_7_CONVERSION_FACTOR(57, 3),

    OTHER_FUEL_USED_8_CONSUMPTION(58, 5),
    OTHER_FUEL_USED_8_NAME(58, 2),
    OTHER_FUEL_USED_8_CONVERSION_FACTOR(58, 3),

    OTHER_FUEL_USED_9_CONSUMPTION(59, 5),
    OTHER_FUEL_USED_9_NAME(59, 2),
    OTHER_FUEL_USED_9_CONVERSION_FACTOR(59, 3),

    OTHER_FUEL_USED_10_CONSUMPTION(60, 5),
    OTHER_FUEL_USED_10_NAME(60, 2),
    OTHER_FUEL_USED_10_CONVERSION_FACTOR(60, 3),

    OTHER_FUEL_USED_11_CONSUMPTION(61, 5),
    OTHER_FUEL_USED_11_NAME(61, 2),
    OTHER_FUEL_USED_11_CONVERSION_FACTOR(61, 3),


    TOTAL_ENERGY(62, 5),
    CHP_DELIVERED_ELECTRICITY(66, 5),
    REPORTING_THROUGHPUT(68, 4),
    ADJUSTED_THROUGHPUT(68, 5),

    // Section 4: Target Period Performance Result
    TARGET_ENERGY_CARBON_THROUGHPUT(101, 4),
    ENERGY_CARBON_THROUGHPUT(102, 4),
    TARGET_PERIOD_ENERGY(105, 4),
    TARGET_PERIOD_IMPROVEMENT_PERCENTAGE(106, 4),
    TARGET_PERIOD_RESULT(108, 4),

    // Section 5: Carbon Surplus or Buy-Out Determination
    TARGET_PERIOD_CARBON_FACTOR(112, 4),
    AMOUNT_ENERGY_USED_UNDER_TARGET(113, 4),
    AMOUNT_CO2_EMITTED_UNDER_TARGET(114, 4),
    CARBON_DIOXIDE_EMITTED(115, 4),
    BANKED_SURPLUS_USED(116, 4),
    SURPLUS_GAINED(117, 4),
    BUY_OUT_REQUIRED(118, 4),
    BUY_OUT_COST(119, 4),

    // Section 5: Supplementary MOA Surplus and Buy-Out Determination
    SUPPLEMENTARY_TARGET_PERIOD_CARBON_FACTOR(123, 4),
    SUPPLEMENTARY_AMOUNT_ENERGY_USED_UNDER_TARGET(124, 4),
    SUPPLEMENTARY_AMOUNT_CO2_EMITTED_UNDER_TARGET(125, 4),
    SUPPLEMENTARY_CARBON_DIOXIDE_EMITTED(126, 4),
    TOTAL_TARGET_PERIOD_BUY_OUT_REQUIRED(127, 4),
    PREVIOUS_BUY_OUT_AFTER_USE_OF_SURPLUS(128, 4),
    PREVIOUS_SURPLUS_USED(129, 4),
    SURPLUS_GAINED_IN_TP(130, 4),
    SECONDARY_BUY_OUT_REQUIRED(131, 4),
    SECONDARY_BUY_OUT_COST(132, 4),
    ;

    private final int rowIndex;
    private final int columnIndex;
}
