import {
  UnderlyingAgreementAcceptedRequestActionPayload,
  UnderlyingAgreementMigratedRequestActionPayload,
  UnderlyingAgreementPayload,
  UnderlyingAgreementRejectedRequestActionPayload,
  UnderlyingAgreementSubmittedRequestActionPayload,
  UnderlyingAgreementVariationAcceptedRequestActionPayload,
  UnderlyingAgreementVariationPayload,
  UnderlyingAgreementVariationRegulatorLedCompletedRequestActionPayload,
  UnderlyingAgreementVariationRejectedRequestActionPayload,
  UnderlyingAgreementVariationSubmittedRequestActionPayload,
} from 'cca-api';

export type UnderlyingAgreementDecisionRequestActionPayload =
  | UnderlyingAgreementAcceptedRequestActionPayload
  | UnderlyingAgreementRejectedRequestActionPayload;

export type UnderlyingAgreementVariationDecisionRequestActionPayload =
  | UnderlyingAgreementVariationAcceptedRequestActionPayload
  | UnderlyingAgreementVariationRejectedRequestActionPayload;

export type UnderlyingAgreementRequestActionPayload =
  | UnderlyingAgreementSubmittedRequestActionPayload
  | UnderlyingAgreementDecisionRequestActionPayload
  | UnderlyingAgreementVariationSubmittedRequestActionPayload
  | UnderlyingAgreementVariationDecisionRequestActionPayload
  | UnderlyingAgreementMigratedRequestActionPayload
  | UnderlyingAgreementVariationRegulatorLedCompletedRequestActionPayload;

export type UnaPayload = UnderlyingAgreementPayload | UnderlyingAgreementVariationPayload;

export type UnATimelineDecisionActionPayload =
  | UnderlyingAgreementDecisionRequestActionPayload
  | UnderlyingAgreementVariationDecisionRequestActionPayload;
