sonar.host.url=http://localhost:9000
sonar.token=sqp_130c30c1fe08f49899d81e6c450144a0ca63769d
sonar.projectKey=uk-cca-app-web-refactor
sonar.projectName=uk-cca-app-web-refactor
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*mock*.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
