package uk.gov.cca.api.workflow.request.core.domain.enumeration;

public enum RequestActionPayloadType {
    RFI_SUBMITTED_PAYLOAD,
    RFI_RESPONSE_SUBMITTED_PAYLOAD,
    
    RDE_SUBMITTED_PAYLOAD,
    RDE_REJECTED_PAYLOAD,
    RDE_DECISION_FORCED_PAYLOAD,

    PAYMENT_MARKED_AS_PAID_PAYLOAD,
    PAYMENT_MARKED_AS_RECEIVED_PAYLOAD,
    PAYMENT_COMPLETED_PAYLOAD,
    PAYMENT_CANCELLED_PAYLOAD
}
