package uk.gov.cca.api.workflow.request.flow.common.service.notification;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaDocumentTemplateGenerationContextActionType {

    // Admin Termination
    public static final String ADMIN_TERMINATION_FINALISED = "ADMIN_TERMINATION_FINALISED";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_FINALISED = "ADMIN_TERMINATION_FINAL_DECISION_FINALISED";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_WITHDRAWN = "ADMIN_TERMINATION_FINAL_DECISION_WITHDRAWN";
    public static final String ADMIN_TERMINATION_WITHDRAWN = "ADMIN_TERMINATION_WITHDRAWN";
    
    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_REJECTED = "UNDERLYING_AGREEMENT_REJECTED";
    public static final String UNDERLYING_AGREEMENT_ACCEPTED = "UNDERLYING_AGREEMENT_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_ACTIVATED = "UNDERLYING_AGREEMENT_ACTIVATED";
    public static final String UNDERLYING_AGREEMENT_ACCEPTED_PROPOSED_DOCUMENT = "UNDERLYING_AGREEMENT_ACCEPTED_PROPOSED_DOCUMENT";
    public static final String UNDERLYING_AGREEMENT_ACTIVATED_FINAL_DOCUMENT = "UNDERLYING_AGREEMENT_ACTIVATED_FINAL_DOCUMENT";
    
    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACCEPTED = "UNDERLYING_AGREEMENT_VARIATION_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PROPOSED_DOCUMENT = "UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PROPOSED_DOCUMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REJECTED = "UNDERLYING_AGREEMENT_VARIATION_REJECTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATED = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATED_FINAL_DOCUMENT = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATED_FINAL_DOCUMENT";
}
