/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAuthorityInfoDTO } from './userAuthorityInfoDTO';

export interface AccountOperatorsUsersAuthoritiesInfoDTO {
  authorities?: Array<UserAuthorityInfoDTO>;
  editable?: boolean;
  contactTypes?: { [key: string]: string };
}
