/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountPerformanceDataStatusInfoDTO {
  targetPeriodType?: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  targetPeriodName?: string;
  locked?: boolean;
  reportVersion?: number;
  editable?: boolean;
}
