/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OtherFuel } from './otherFuel';

export interface ActualTargetPeriodPerformance {
  actualTuIdentifier: string;
  actualThroughput: string;
  energyData?: Record<string, string>;
  carbonFactors?: OtherFuel[];
  tpEnergy: string;
  tpChpDeliveredElectricity: string;
  reportingThroughput: string;
  adjustedThroughput?: string;
}
