/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AdditionalNoticeRecipientDTO {
  firstName?: string;
  lastName?: string;
  email?: string;
  type?: 'RESPONSIBLE_PERSON' | 'ADMINISTRATIVE_CONTACT' | 'SECTOR_CONTACT' | 'SECTOR_USER' | 'OPERATOR';
  userId?: string;
}
