/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminTerminationWithdrawReasonDetails } from './adminTerminationWithdrawReasonDetails';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface AdminTerminationWithdrawSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  adminTerminationWithdrawReasonDetails: AdminTerminationWithdrawReasonDetails;
  decisionNotification: CcaDecisionNotification;
  adminTerminationWithdrawAttachments?: { [key: string]: string };
  usersInfo?: { [key: string]: RequestActionUserInfo };
  defaultContacts: Array<DefaultNoticeRecipient>;
  officialNotice: FileInfoDTO;
}
