/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CcaPeerReviewDecision } from './ccaPeerReviewDecision';
import { AdminTerminationReasonDetails } from './adminTerminationReasonDetails';

export interface AdminTerminationPeerReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  adminTerminationReasonDetails?: AdminTerminationReasonDetails;
  sectionsCompleted?: Record<string, string>;
  adminTerminationAttachments?: Record<string, string>;
  decision?: CcaPeerReviewDecision;
  peerReviewAttachments?: Record<string, string>;
}
