/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminTerminationReasonDetails } from './adminTerminationReasonDetails';

export interface AdminTerminationSaveRequestTaskActionPayload {
  payloadType?: string;
  adminTerminationReasonDetails?: AdminTerminationReasonDetails;
  sectionsCompleted?: Record<string, string>;
}
