/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestActionUserInfo } from './requestActionUserInfo';
import { AdminTerminationFinalDecisionReasonDetails } from './adminTerminationFinalDecisionReasonDetails';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { FileInfoDTO } from './fileInfoDTO';

export interface AdminTerminationFinalDecisionSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  adminTerminationFinalDecisionReasonDetails: AdminTerminationFinalDecisionReasonDetails;
  decisionNotification: CcaDecisionNotification;
  adminTerminationFinalDecisionAttachments?: Record<string, string>;
  usersInfo?: Record<string, RequestActionUserInfo>;
  defaultContacts: DefaultNoticeRecipient[];
  officialNotice: FileInfoDTO;
}
