/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminTerminationWithdrawReasonDetails } from './adminTerminationWithdrawReasonDetails';

export interface AdminTerminationWithdrawSaveRequestTaskActionPayload {
  payloadType?: string;
  adminTerminationWithdrawReasonDetails?: AdminTerminationWithdrawReasonDetails;
  sectionsCompleted?: Record<string, string>;
}
