/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorrectiveActionFollowUpResponse } from './correctiveActionFollowUpResponse';

export interface AuditTrackCorrectiveActionsSaveRequestTaskActionPayload {
  payloadType?: string;
  actionTitle: string;
  correctiveActionFollowUpResponse?: CorrectiveActionFollowUpResponse;
  sectionsCompleted?: Record<string, string>;
}
