/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDetailsAndCorrectiveActions } from './auditDetailsAndCorrectiveActions';

export interface AuditDetailsCorrectiveActionsSubmitSaveRequestTaskActionPayload {
  payloadType?: string;
  auditDetailsAndCorrectiveActions?: AuditDetailsAndCorrectiveActions;
  sectionsCompleted?: Record<string, string>;
}
