/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AuditReasonDetails {
  reasonsForAudit: (
    'ELIGIBILITY' | 'SEVENTY_RULE_EVALUATION' | 'BASE_YEAR_DATA' | 'REPORTING_DATA' | 'NON_COMPLIANCE' | 'OTHER'
  )[];
  comment: string;
}
