/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditTrackCorrectiveActions } from './auditTrackCorrectiveActions';

export interface AuditTrackCorrectiveActionsRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  auditTrackCorrectiveActions: AuditTrackCorrectiveActions;
  respondedActions?: string[];
  sectionsCompleted?: Record<string, string>;
  facilityAuditAttachments?: Record<string, string>;
}
