/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AuditDetails {
  auditTechnique: 'DESK_BASED_INTERVIEW' | 'ON_SITE_VISIT';
  auditDate: string;
  comments: string;
  finalAuditReportDate: string;
  auditDocuments: string[];
}
