/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDetails } from './auditDetails';
import { CorrectiveActions } from './correctiveActions';

export interface AuditDetailsAndCorrectiveActions {
  auditDetails: AuditDetails;
  correctiveActions: CorrectiveActions;
}
