/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BaselineData {
  isTwelveMonths: boolean;
  baselineDate: string;
  explanation?: string;
  greenfieldEvidences?: string[];
  energy: string;
  usedReportingMechanism?: boolean;
  throughput?: string;
  performance?: string;
  energyCarbonFactor: string;
}
