/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyOutSurplusTransactionListItemDTO } from './buyOutSurplusTransactionListItemDTO';

export interface BuyOutSurplusTransactionsListDTO {
  transactions?: BuyOutSurplusTransactionListItemDTO[];
  total?: number;
}
