/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BuyOutSurplusTransactionHistoryPayload {
  comments?: string;
  evidenceFiles?: Record<string, string>;
  type: 'AMOUNT_CHANGED' | 'PAYMENT_STATUS_CHANGED';
}
