/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The Transaction Update Amount
 */
export interface BuyOutSurplusTransactionUpdateAmountDTO {
  amount: string;
  comments: string;
  evidenceFiles?: Record<string, string>;
}
