/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';

export interface BuyOutSurplusDetails {
  targetPeriodType: 'TP5' | 'TP6';
  performanceDataReportVersion: number;
  submissionType: 'PRIMARY' | 'SECONDARY';
  tpOutcome: 'TARGET_MET' | 'BUY_OUT_REQUIRED' | 'SURPLUS_USED_BUY_OUT_REQUIRED' | 'SURPLUS_USED' | 'OUTSTANDING';
  paymentStatus?:
    | 'AWAITING_PAYMENT'
    | 'AWAITING_REFUND'
    | 'PAID'
    | 'REFUNDED'
    | 'NOT_REQUIRED'
    | 'UNDER_APPEAL'
    | 'TERMINATED';
  transactionCode?: string;
  officialNotice?: FileInfoDTO;
  dueDate?: string;
  runId: string;
}
