/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CarbonSurplusBuyOutDTO {
  co2Emissions?: string;
  surplusUsed?: string;
  surplusGained?: string;
  priBuyOutCarbon?: string;
  priBuyOutCost?: string;
}
