/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilityBaseInfoDTO } from './facilityBaseInfoDTO';

export interface Cca2TerminationAccountProcessingSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  excludedFacilities?: FacilityBaseInfoDTO[];
}
