/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilityBaselineData } from './facilityBaselineData';
import { FacilityBaselineEnergyConsumption } from './facilityBaselineEnergyConsumption';
import { FacilityTargetComposition } from './facilityTargetComposition';
import { FacilityTargets } from './facilityTargets';

export interface Cca3FacilityBaselineAndTargets {
  targetComposition: FacilityTargetComposition;
  baselineData: FacilityBaselineData;
  facilityBaselineEnergyConsumption: FacilityBaselineEnergyConsumption;
  facilityTargets: FacilityTargets;
}
