/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails } from './cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails';

export interface Cca3ExistingFacilitiesMigrationAccountProcessingActivationRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  activationDetails?: Cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails;
  sectionsCompleted?: Record<string, string>;
  activationAttachments?: Record<string, string>;
}
