/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cca3FacilityMigrationData } from './cca3FacilityMigrationData';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';

export interface Cca3ExistingFacilitiesMigrationAccountProcessingSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  facilityMigrationDataList?: Cca3FacilityMigrationData[];
  defaultContacts?: DefaultNoticeRecipient[];
  officialNotice?: FileInfoDTO;
  underlyingAgreementDocument?: FileInfoDTO;
}
