/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails } from './cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface Cca3ExistingFacilitiesMigrationAccountProcessingActivatedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  activationDetails: Cca3ExistingFacilitiesMigrationAccountProcessingActivationDetails;
  activationAttachments?: Record<string, string>;
  decisionNotification: CcaDecisionNotification;
  defaultContacts: DefaultNoticeRecipient[];
  usersInfo?: Record<string, RequestActionUserInfo>;
  officialNotice: FileInfoDTO;
  underlyingAgreementDocument: FileInfoDTO;
}
