/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilityTargetComposition } from './facilityTargetComposition';
import { FacilityTargets } from './facilityTargets';
import { FacilityBaselineData } from './facilityBaselineData';

export interface Cca3FacilityBaselineAndTargets {
  targetComposition: FacilityTargetComposition;
  baselineData: FacilityBaselineData;
  facilityTargets: FacilityTargets;
}
