/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDTO } from './userInfoDTO';

export interface CcaItemDTO {
  creationDate?: string;
  requestId?: string;
  requestType?: string;
  taskId?: number;
  taskAssignee?: UserInfoDTO;
  taskAssigneeType?: string;
  taskType?: string;
  daysRemaining?: number;
  accountId?: number;
  accountName?: string;
  businessId?: string;
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  sectorId?: number;
  sectorAcronym?: string;
  sectorName?: string;
  facilityId?: number;
  facilityBusinessId?: string;
  siteName?: string;
  _new?: boolean;
  isNew?: boolean;
}
