/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The MI report user defined DTO
 */
export interface CcaMiReportUserDefinedDTO {
  reportName: string;
  description?: string;
  queryDefinition: string;
}
