/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorrectiveAction } from './correctiveAction';

export interface CorrectiveActions {
  hasActions: boolean;
  actions?: CorrectiveAction[];
}
