/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DefaultNoticeRecipient {
  name: string;
  email: string;
  recipientType:
    | 'RESPONSIBLE_PERSON'
    | 'ADMINISTRATIVE_CONTACT'
    | 'SECTOR_CONTACT'
    | 'SECTOR_USER'
    | 'SECTOR_CONSULTANT'
    | 'OPERATOR';
}
