/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DocumentTemplateDTO {
  id?: number;
  name?: string;
  workflow?: string;
  lastUpdatedDate?: string;
  notificationTemplateId?: number;
  fileUuid?: string;
  filename?: string;
}
