/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilityAddressDTO } from './facilityAddressDTO';

export interface FacilityDetails {
  name: string;
  isCoveredByUkets: boolean;
  uketsId?: string;
  applicationReason: 'NEW_AGREEMENT' | 'CHANGE_OF_OWNERSHIP';
  previousFacilityId?: string;
  participatingSchemeVersions: ('CCA_2' | 'CCA_3')[];
  facilityAddress: FacilityAddressDTO;
}
