/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityUploadCsvData } from './performanceDataFacilityUploadCsvData';

export interface FacilityUploadReport {
  facilityId?: number;
  facilityBusinessId?: string;
  accountId?: number;
  csvFileName?: string;
  csvData?: PerformanceDataFacilityUploadCsvData;
  succeeded?: boolean;
  errors?: string[];
}
