/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FacilityAuditViewDTO {
  auditRequired?: boolean;
  reasons?: (
    'ELIGIBILITY' | 'SEVENTY_RULE_EVALUATION' | 'BASE_YEAR_DATA' | 'REPORTING_DATA' | 'NON_COMPLIANCE' | 'OTHER'
  )[];
  comments?: string;
  editable?: boolean;
}
