/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityCalculatedResults } from './performanceDataFacilityCalculatedResults';
import { PerformanceDataFacilityBaselineAndTargets } from './performanceDataFacilityBaselineAndTargets';

export interface FacilityPerformanceDataReportDetailsDTO {
  targetPeriod?: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  atLeastSeventyPercentEnergyUsed?: boolean;
  calculatedResults?: PerformanceDataFacilityCalculatedResults;
  baselineAndTargets?: PerformanceDataFacilityBaselineAndTargets;
}
