/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FacilityPerformanceAccountTemplateProcessingRequestMetadata {
  type?: string;
  targetYear?: number;
  submittedDate?: string;
  uploadRequestId?: string;
}
