/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductVariableEnergyConsumptionData } from './productVariableEnergyConsumptionData';

export interface FacilityBaselineEnergyConsumption {
  totalFixedEnergy: string;
  hasVariableEnergy: boolean;
  variableEnergyType?: 'TOTALS' | 'BY_PRODUCT';
  baselineVariableEnergy?: string;
  totalThroughput?: string;
  throughputUnit?: string;
  variableEnergyConsumptionDataByProduct?: ProductVariableEnergyConsumptionData[];
}
