/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilityAddressDTO } from './facilityAddressDTO';
import { FacilityCertificationDetailsDTO } from './facilityCertificationDetailsDTO';

export interface FacilityInfoDTO {
  facilityId?: number;
  facilityBusinessId?: string;
  status?: 'LIVE' | 'INACTIVE';
  chargeStartDate?: string;
  siteName?: string;
  schemeExitDate?: string;
  address?: FacilityAddressDTO;
  facilityCertificationDetails?: FacilityCertificationDetailsDTO[];
}
