/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountAddressDTO } from './accountAddressDTO';

export interface FacilityDataDetailsDTO {
  facilityId?: string;
  status?: 'LIVE' | 'INACTIVE';
  chargeStartDate?: string;
  siteName?: string;
  schemeExitDate?: string;
  address?: AccountAddressDTO;
}
