/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacilitySearchResultExtendedDTO } from './facilitySearchResultExtendedDTO';

export interface FacilitySearchResults {
  facilities?: FacilitySearchResultExtendedDTO[];
  total?: number;
}
