/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountUploadReport } from './accountUploadReport';
import { NotAccountRelatedUploadErrorReport } from './notAccountRelatedUploadErrorReport';

export interface FileReports {
  accountFileReports?: Record<string, AccountUploadReport>;
  notAccountRelatedFileErrors?: NotAccountRelatedUploadErrorReport[];
  readonly numberOfFilesFailed?: number;
  readonly numberOfFilesSucceeded?: number;
}
