/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface HttpHeadersAcceptLanguageAsLocalesInner {
  language?: string;
  displayName?: string;
  country?: string;
  variant?: string;
  script?: string;
  unicodeLocaleAttributes?: string[];
  unicodeLocaleKeys?: string[];
  displayLanguage?: string;
  displayScript?: string;
  displayCountry?: string;
  displayVariant?: string;
  extensionKeys?: string[];
  iso3Language?: string;
  iso3Country?: string;
}
