/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeadersHostAddress } from './httpHeadersHostAddress';

export interface HttpHeadersHost {
  hostString?: string;
  address?: HttpHeadersHostAddress;
  port?: number;
  unresolved?: boolean;
  hostName?: string;
}
