/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './contentDisposition';
import { HttpHeadersAcceptLanguageAsLocalesInner } from './httpHeadersAcceptLanguageAsLocalesInner';
import { HttpHeadersAcceptLanguageInner } from './httpHeadersAcceptLanguageInner';
import { HttpHeadersHost } from './httpHeadersHost';
import { MediaType } from './mediaType';

export interface HttpHeaders {
  [key: string]: string[] | any;

  allow?: object[];
  acceptLanguage?: HttpHeadersAcceptLanguageInner[];
  accept?: MediaType[];
  acceptLanguageAsLocales?: HttpHeadersAcceptLanguageAsLocalesInner[];
  acceptPatch?: MediaType[];
  accessControlAllowCredentials?: boolean;
  accessControlAllowHeaders?: string[];
  accessControlAllowMethods?: object[];
  accessControlAllowOrigin?: string;
  accessControlExposeHeaders?: string[];
  accessControlMaxAge?: number;
  accessControlRequestHeaders?: string[];
  accessControlRequestMethod?: object;
  acceptCharset?: string[];
  etag?: string;
  expires?: number;
  ifMatch?: string[];
  ifNoneMatch?: string[];
  ifUnmodifiedSince?: number;
  pragma?: string;
  range?: object[];
  upgrade?: string;
  vary?: string[];
  contentDisposition?: ContentDisposition;
  empty?: boolean;
  location?: string;
  host?: HttpHeadersHost;
  all?: Record<string, string>;
  lastModified?: number;
  date?: number;
  contentLength?: number;
  origin?: string;
  contentLanguage?: HttpHeadersAcceptLanguageAsLocalesInner;
  bearerAuth?: string;
  basicAuth?: string;
  cacheControl?: string;
  connection?: string[];
  ifModifiedSince?: number;
  contentType?: MediaType;
}
