/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './contentDisposition';
import { HttpHeadersAcceptLanguage } from './httpHeadersAcceptLanguage';
import { HttpHeadersAcceptLanguageAsLocales } from './httpHeadersAcceptLanguageAsLocales';
import { HttpHeadersHost } from './httpHeadersHost';
import { MediaType } from './mediaType';

export interface HttpHeaders {
  [key: string]: Array<string> | any;

  origin?: string;
  allow?: Array<object>;
  accept?: Array<MediaType>;
  acceptLanguageAsLocales?: Array<HttpHeadersAcceptLanguageAsLocales>;
  acceptLanguage?: Array<HttpHeadersAcceptLanguage>;
  acceptPatch?: Array<MediaType>;
  accessControlAllowCredentials?: boolean;
  accessControlAllowHeaders?: Array<string>;
  accessControlAllowMethods?: Array<object>;
  accessControlAllowOrigin?: string;
  accessControlExposeHeaders?: Array<string>;
  accessControlMaxAge?: number;
  accessControlRequestHeaders?: Array<string>;
  accessControlRequestMethod?: object;
  acceptCharset?: Array<string>;
  contentDisposition?: ContentDisposition;
  etag?: string;
  expires?: number;
  ifMatch?: Array<string>;
  ifNoneMatch?: Array<string>;
  ifUnmodifiedSince?: number;
  pragma?: string;
  range?: Array<object>;
  upgrade?: string;
  vary?: Array<string>;
  empty?: boolean;
  location?: string;
  host?: HttpHeadersHost;
  all?: { [key: string]: string };
  lastModified?: number;
  date?: number;
  contentLength?: number;
  bearerAuth?: string;
  basicAuth?: string;
  contentLanguage?: HttpHeadersAcceptLanguageAsLocales;
  cacheControl?: string;
  connection?: Array<string>;
  ifModifiedSince?: number;
  contentType?: MediaType;
}
