/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './contentDisposition';
import { HttpHeadersHost } from './httpHeadersHost';
import { MediaType } from './mediaType';
import { HttpHeadersAcceptLanguageAsLocales } from './httpHeadersAcceptLanguageAsLocales';
import { HttpHeadersAcceptLanguage } from './httpHeadersAcceptLanguage';

export interface HttpHeaders {
  [key: string]: string[] | any;

  allow?: object[];
  acceptLanguage?: HttpHeadersAcceptLanguage[];
  accept?: MediaType[];
  acceptLanguageAsLocales?: HttpHeadersAcceptLanguageAsLocales[];
  acceptPatch?: MediaType[];
  accessControlAllowCredentials?: boolean;
  accessControlAllowHeaders?: string[];
  accessControlAllowMethods?: object[];
  accessControlAllowOrigin?: string;
  accessControlExposeHeaders?: string[];
  accessControlMaxAge?: number;
  accessControlRequestHeaders?: string[];
  accessControlRequestMethod?: object;
  acceptCharset?: string[];
  contentDisposition?: ContentDisposition;
  etag?: string;
  expires?: number;
  ifMatch?: string[];
  ifNoneMatch?: string[];
  ifUnmodifiedSince?: number;
  pragma?: string;
  range?: object[];
  upgrade?: string;
  vary?: string[];
  empty?: boolean;
  location?: string;
  host?: HttpHeadersHost;
  all?: Record<string, string>;
  lastModified?: number;
  date?: number;
  contentLength?: number;
  origin?: string;
  contentLanguage?: HttpHeadersAcceptLanguageAsLocales;
  bearerAuth?: string;
  basicAuth?: string;
  cacheControl?: string;
  connection?: string[];
  ifModifiedSince?: number;
  contentType?: MediaType;
}
