/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceEnforcementResponseNotice } from './nonComplianceEnforcementResponseNotice';

export interface NonComplianceEnforcementResponseNoticeSaveRequestTaskActionPayload {
  payloadType?: string;
  enforcementResponseNotice?: NonComplianceEnforcementResponseNotice;
  sectionsCompleted?: Record<string, string>;
}
