/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NonComplianceEnforcementResponseNotice {
  type: 'PENALTY' | 'PENALTY_WAIVER';
  file: string;
  comments?: string;
}
