/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestActionUserInfo } from './requestActionUserInfo';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { DecisionNotification } from './decisionNotification';
import { NonComplianceEnforcementResponseNotice } from './nonComplianceEnforcementResponseNotice';

export interface NonComplianceEnforcementResponseNoticeSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  enforcementResponseNotice: NonComplianceEnforcementResponseNotice;
  decisionNotification: DecisionNotification;
  nonComplianceAttachments?: Record<string, string>;
  usersInfo?: Record<string, RequestActionUserInfo>;
  defaultContacts: DefaultNoticeRecipient[];
}
