/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CcaPeerReviewDecision } from './ccaPeerReviewDecision';
import { NonComplianceCloseJustification } from './nonComplianceCloseJustification';
import { NonComplianceNoticeOfIntent } from './nonComplianceNoticeOfIntent';

export interface NonComplianceNoticeOfIntentPeerReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  noticeOfIntent?: NonComplianceNoticeOfIntent;
  closeJustification?: NonComplianceCloseJustification;
  sectionsCompleted?: Record<string, string>;
  nonComplianceAttachments?: Record<string, string>;
  decision?: CcaPeerReviewDecision;
  peerReviewAttachments?: Record<string, string>;
}
