/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceAppealOutcomeDetails } from './nonComplianceAppealOutcomeDetails';

export interface NonComplianceAppealOutcomeSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  appealOutcome: NonComplianceAppealOutcomeDetails;
  nonComplianceAttachments?: Record<string, string>;
}
