/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoticeOfIntent } from './noticeOfIntent';

export interface NonComplianceNoticeOfIntentSubmitSaveRequestTaskActionPayload {
  payloadType?: string;
  noticeOfIntent?: NoticeOfIntent;
  sectionsCompleted?: Record<string, string>;
}
