/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CcaPeerReviewDecision } from './ccaPeerReviewDecision';
import { NonComplianceCloseJustification } from './nonComplianceCloseJustification';
import { NonComplianceEnforcementResponseNotice } from './nonComplianceEnforcementResponseNotice';

export interface NonComplianceEnforcementResponseNoticePeerReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  enforcementResponseNotice?: NonComplianceEnforcementResponseNotice;
  closeJustification?: NonComplianceCloseJustification;
  penaltyReissue?: boolean;
  sectionsCompleted?: Record<string, string>;
  nonComplianceAttachments?: Record<string, string>;
  decision?: CcaPeerReviewDecision;
  peerReviewAttachments?: Record<string, string>;
}
