/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowFacilityDTO } from './workflowFacilityDTO';

export interface NonComplianceDetails {
  nonComplianceType:
    | 'FAILURE_TO_PROVIDE_TPR'
    | 'FAILURE_TO_PROVIDE_PR'
    | 'FAILURE_TO_PROVIDE_OTHER_INFO'
    | 'FAILURE_TO_NOTIFY_OF_AN_ERROR'
    | 'FAILURE_TO_NOTIFY_FACILITY_NO_LONGER_ELIGIBLE'
    | 'FAILURE_TO_NOTIFY_OTHER_REQUIREMENT_UNA'
    | 'INACCURATE_TPR_INFO'
    | 'INACCURATE_PR_INFO'
    | 'INACCURATE_OTHER_INFO';
  nonCompliantDate?: string;
  compliantDate?: string;
  comment?: string;
  relevantWorkflows?: string[];
  relevantFacilities?: WorkflowFacilityDTO[];
  isEnforcementResponseNoticeRequired: boolean;
  explanation?: string;
}
