/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceConclusion } from './nonComplianceConclusion';

export interface NonComplianceConclusionSaveRequestTaskActionPayload {
  payloadType?: string;
  nonComplianceConclusion?: NonComplianceConclusion;
  sectionsCompleted?: Record<string, string>;
}
