/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceDetails } from './nonComplianceDetails';

export interface NonComplianceDetailsSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  nonComplianceDetails: NonComplianceDetails;
  allRelevantWorkflows?: Record<string, string>;
  allRelevantFacilities?: Record<string, string>;
  sectionsCompleted?: Record<string, string>;
}
