/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { NonComplianceNoticeOfIntent } from './nonComplianceNoticeOfIntent';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface NonComplianceNoticeOfIntentSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  noticeOfIntent: NonComplianceNoticeOfIntent;
  decisionNotification: DecisionNotification;
  nonComplianceAttachments?: Record<string, string>;
  usersInfo?: Record<string, RequestActionUserInfo>;
  defaultContacts: DefaultNoticeRecipient[];
}
