/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneNumberDTO } from './phoneNumberDTO';

/**
 * The userRegistrationDTO
 */
export interface OperatorUserRegistrationWithCredentialsDTO {
  emailToken: string;
  firstName: string;
  lastName: string;
  phoneNumber?: PhoneNumberDTO;
  mobileNumber?: PhoneNumberDTO;
  termsVersion?: number;
  password: string;
}
