/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OutstandingRequestTask {
  requestTaskAssignee?: string;
  Account_ID?: string;
  Account_name?: string;
  Legal_Entity_name?: string;
  Workflow_ID?: string;
  Workflow_type?: 'DUMMY_REQUEST_TYPE';
  Workflow_task_name?: 'DUMMY_REQUEST_TYPE_APPLICATION_REVIEW' | 'DUMMY_REQUEST_TASK_TYPE2';
  Workflow_task_assignee?: string;
  Workflow_task_due_date?: string;
  Workflow_task_days_remaining?: number;
}
