/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetPeriodDetailsDTO } from './targetPeriodDetailsDTO';
import { TargetPeriodYear } from './targetPeriodYear';

export interface PerformanceDataFacilityDataUploadRequestMetadata {
  type?: string;
  targetPeriodType?: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  reportType?: 'INTERIM' | 'FINAL';
  targetPeriodYear?: TargetPeriodYear;
  targetPeriods?: TargetPeriodDetailsDTO[];
  submissionType?: 'PRIMARY' | 'SECONDARY';
  submittedDate?: string;
}
