/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyOrCarbonSavingActionsAndMeasuresImplementedItem } from './energyOrCarbonSavingActionsAndMeasuresImplementedItem';
import { FileInfoDTO } from './fileInfoDTO';
import { TargetUnitIdentityAndPerformance } from './targetUnitIdentityAndPerformance';

export interface PerformanceAccountTemplateDataContainer {
  targetUnitIdentityAndPerformance: TargetUnitIdentityAndPerformance;
  energyOrCarbonSavingActionsAndMeasuresImplementedItems?: EnergyOrCarbonSavingActionsAndMeasuresImplementedItem[];
  file: FileInfoDTO;
}
