/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { SectorAssociationInfo } from './sectorAssociationInfo';

export interface PerformanceDataDownloadSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  sectorAssociationInfo?: SectorAssociationInfo;
  targetPeriodType?: 'TP6';
  zipFile?: FileInfoDTO;
  errorsFile?: FileInfoDTO;
  processCompleted?: boolean;
  errorMessage?: string;
}
