/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceDataFacilityUploadCsvData {
  facilityBusinessId?: string;
  gridElectricity?: string;
  nonGridElectricity?: string;
  naturalGas?: string;
  lpg?: string;
  gasDieselOil?: string;
  fuelOil?: string;
  kerosene?: string;
  coal?: string;
  coke?: string;
  petrol?: string;
  nitrogen?: string;
  carbonDioxide?: string;
  ethane?: string;
  naphtha?: string;
  petroleumCoke?: string;
  refineryGas?: string;
  otherFuelName1?: string;
  otherFuelConversionFactor1?: string;
  otherFuelAmount1?: string;
  otherFuelName2?: string;
  otherFuelConversionFactor2?: string;
  otherFuelAmount2?: string;
  otherFuelName3?: string;
  otherFuelConversionFactor3?: string;
  otherFuelAmount3?: string;
  otherFuelName4?: string;
  otherFuelConversionFactor4?: string;
  otherFuelAmount4?: string;
  otherFuelName5?: string;
  otherFuelConversionFactor5?: string;
  otherFuelAmount5?: string;
  otherFuelName6?: string;
  otherFuelConversionFactor6?: string;
  otherFuelAmount6?: string;
  otherFuelName7?: string;
  otherFuelConversionFactor7?: string;
  otherFuelAmount7?: string;
  otherFuelName8?: string;
  otherFuelConversionFactor8?: string;
  otherFuelAmount8?: string;
  otherFuelName9?: string;
  otherFuelConversionFactor9?: string;
  otherFuelAmount9?: string;
  otherFuelName10?: string;
  otherFuelConversionFactor10?: string;
  otherFuelAmount10?: string;
  atLeastSeventyPercentEnergyUsed?: boolean;
  electricitySuppliedFromCHP?: string;
  actualThroughput?: string;
  productName1?: string;
  productActualThroughput1?: string;
  productName2?: string;
  productActualThroughput2?: string;
  productName3?: string;
  productActualThroughput3?: string;
  productName4?: string;
  productActualThroughput4?: string;
  productName5?: string;
  productActualThroughput5?: string;
  productName6?: string;
  productActualThroughput6?: string;
  productName7?: string;
  productActualThroughput7?: string;
  productName8?: string;
  productActualThroughput8?: string;
  productName9?: string;
  productActualThroughput9?: string;
  productName10?: string;
  productActualThroughput10?: string;
  productName11?: string;
  productActualThroughput11?: string;
  productName12?: string;
  productActualThroughput12?: string;
  productName13?: string;
  productActualThroughput13?: string;
  productName14?: string;
  productActualThroughput14?: string;
  productName15?: string;
  productActualThroughput15?: string;
  productName16?: string;
  productActualThroughput16?: string;
  productName17?: string;
  productActualThroughput17?: string;
  productName18?: string;
  productActualThroughput18?: string;
  productName19?: string;
  productActualThroughput19?: string;
  productName20?: string;
  productActualThroughput20?: string;
}
