/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceDataFacilitySubmissionDetails {
  targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  reportType: 'INTERIM' | 'FINAL';
  targetPeriodYear: number;
  submissionType?: 'PRIMARY' | 'SECONDARY';
  reportVersion: number;
  creationDate: string;
  submissionDate: string;
}
