/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { FileReports } from './fileReports';

export interface PerformanceAccountTemplateDataUploadSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  reportPackages: string[];
  fileReports?: FileReports;
  csvReportFile?: FileInfoDTO;
  processingStatus?: 'NOT_STARTED_YET' | 'IN_PROGRESS' | 'COMPLETED';
  errorType?: 'CSV_GENERATION_FAILED' | 'REPORT_PACKAGE_MISSING' | 'EXTRACT_VALIDATE_PERSIST_GENERIC_ERROR';
  uploadAttachments?: Record<string, string>;
}
