/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityUpload } from './performanceDataFacilityUpload';
import { PerformanceDataFacilityUploadResults } from './performanceDataFacilityUploadResults';

export interface PerformanceDataFacilityDataUploadCompletedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  performanceDataUpload: PerformanceDataFacilityUpload;
  results: PerformanceDataFacilityUploadResults;
  uploadAttachments: Record<string, string>;
}
