/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityCalculatedResults } from './performanceDataFacilityCalculatedResults';
import { PerformanceDataFacilityEnergyFuelDetails } from './performanceDataFacilityEnergyFuelDetails';
import { PerformanceDataFacilityThroughputDetails } from './performanceDataFacilityThroughputDetails';
import { PerformanceDataFacilityBaselineAndTargets } from './performanceDataFacilityBaselineAndTargets';

export interface PerformanceDataFacilityContainer {
  baselineAndTargets: PerformanceDataFacilityBaselineAndTargets;
  energyFuelDetails: PerformanceDataFacilityEnergyFuelDetails;
  throughputDetails: PerformanceDataFacilityThroughputDetails;
  calculatedResults: PerformanceDataFacilityCalculatedResults;
}
