/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceData } from './performanceData';
import { FileInfoDTO } from './fileInfoDTO';

export interface PerformanceDataSpreadsheetProcessingSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  performanceDataTargetPeriodType?: 'TP6';
  accountReportFile?: FileInfoDTO;
  performanceData?: PerformanceData;
}
