/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceDataCalculatedMetrics {
  byPerformance?: string;
  numericalTarget?: string;
  tolerance?: string;
  tpEnergy?: string;
  tpChpDeliveredElectricity?: string;
  tpPerformance?: string;
  tpPerformancePercent?: string;
  tpOutcome?: 'TARGET_MET' | 'BUY_OUT_REQUIRED' | 'SURPLUS_USED_BUY_OUT_REQUIRED' | 'SURPLUS_USED' | 'OUTSTANDING';
  tpCarbonFactor?: string;
  energyCarbonUnderTarget?: string;
  carbonUnderTarget?: string;
  co2Emissions?: string;
  surplusUsed?: string;
  surplusGained?: string;
  priBuyOutCarbon?: string;
  priBuyOutCost?: string;
  secondaryBuyOutCo2?: string;
  secondaryBuyOutCost?: string;
}
