/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceDataFacilityCalculatedResults {
  actualEnergyCarbon: string;
  targetEnergyCarbon: string;
  energyCarbonDifference: string;
  targetImprovement: string;
  weightedConversionFactor: string;
  targetCo2Emissions: string;
  actualCo2Emissions: string;
  co2EmissionsDifference: string;
  actualImprovement: string;
  targetPeriodResultType?: 'TARGET_MET' | 'TARGET_NOT_MET';
  surplusGained?: string;
  buyOutRequired?: string;
}
