/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityCalculatedResults } from './performanceDataFacilityCalculatedResults';
import { PerformanceDataFacilityInputEnergyFuelDetails } from './performanceDataFacilityInputEnergyFuelDetails';
import { PerformanceDataFacilityThroughputDetails } from './performanceDataFacilityThroughputDetails';

export interface PerformanceDataFacilityInputData {
  energyFuelDetails: PerformanceDataFacilityInputEnergyFuelDetails;
  throughputDetails: PerformanceDataFacilityThroughputDetails;
  calculatedResults?: PerformanceDataFacilityCalculatedResults;
}
