/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { PerformanceDataUpload } from './performanceDataUpload';
import { SectorAssociationInfo } from './sectorAssociationInfo';
import { TargetUnitAccountUploadReport } from './targetUnitAccountUploadReport';

export interface PerformanceDataUploadSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  sectorAssociationInfo?: SectorAssociationInfo;
  performanceDataUpload?: PerformanceDataUpload;
  processCompleted?: boolean;
  errorMessage?: string;
  csvFile?: FileInfoDTO;
  totalFilesUploaded?: number;
  filesSucceeded?: number;
  filesFailed?: number;
  errors?: Record<string, string>;
  accountReports?: Record<string, TargetUnitAccountUploadReport>;
  performanceDataUploadAttachments?: Record<string, string>;
}
