/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceDataFacilityContainer } from './performanceDataFacilityContainer';
import { PerformanceDataFacilitySubmissionDetails } from './performanceDataFacilitySubmissionDetails';

export interface PerformanceDataFacilitySubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  details: PerformanceDataFacilitySubmissionDetails;
  performanceData: PerformanceDataFacilityContainer;
}
