/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreAuditReviewDetails } from './preAuditReviewDetails';

export interface PreAuditReviewSubmitSaveRequestTaskActionPayload {
  payloadType?: string;
  preAuditReviewDetails?: PreAuditReviewDetails;
  sectionsCompleted?: Record<string, string>;
}
