/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PrimaryDetermination {
  tpCarbonFactor: string;
  energyCarbonUnderTarget: string;
  carbonUnderTarget: string;
  co2Emissions: string;
  surplusUsed: string;
  surplusGained: string;
  priBuyOutCarbon: string;
  priBuyOutCost: string;
}
