/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdeResponsePayload } from './rdeResponsePayload';
import { RdeForceDecisionPayload } from './rdeForceDecisionPayload';

export interface RdeForceDecisionRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  rdeResponsePayload: RdeResponsePayload;
  rdeForceDecisionPayload: RdeForceDecisionPayload;
  rdeAttachments?: Record<string, string>;
}
