/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdePayload } from './rdePayload';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface RdeSubmitRequestTaskActionPayload extends RequestTaskActionPayload {
  rdePayload: RdePayload;
}
