/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestDetailsDTO {
  id?: string;
  requestType?: 'DUMMY_REQUEST_TYPE';
  requestStatus?:
    | 'IN_PROGRESS'
    | 'COMPLETED'
    | 'CANCELLED'
    | 'WITHDRAWN'
    | 'APPROVED'
    | 'REJECTED'
    | 'CLOSED'
    | 'EXEMPT';
  creationDate?: string;
  requestMetadata?: RequestMetadata;
}
