/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestTaskActionPayload {
  payloadType?:
    | 'RFI_SUBMIT_PAYLOAD'
    | 'RFI_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_SUBMIT_PAYLOAD'
    | 'RDE_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_FORCE_DECISION_PAYLOAD'
    | 'PAYMENT_MARK_AS_RECEIVED_PAYLOAD'
    | 'PAYMENT_CANCEL_PAYLOAD'
    | 'EMPTY_PAYLOAD';
}
