/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestTaskPayload {
  payloadType?:
    | 'RFI_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_WAIT_FOR_RESPONSE_PAYLOAD'
    | 'PAYMENT_MAKE_PAYLOAD'
    | 'PAYMENT_TRACK_PAYLOAD'
    | 'PAYMENT_CONFIRM_PAYLOAD';
}
