/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The search criteria
 */
export interface RequestSearchByAccountCriteria {
  accountId: number;
  requestTypes?: Array<'DUMMY_REQUEST_TYPE'>;
  requestStatuses?: Array<
    'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'WITHDRAWN' | 'APPROVED' | 'REJECTED' | 'CLOSED' | 'EXEMPT'
  >;
  category: 'PERMIT' | 'REPORTING' | 'CA';
  pageNumber: number;
  pageSize: number;
}
