/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The request task attachment properties
 */
export interface RequestTaskAttachmentActionProcessDTO {
  requestTaskId: number;
  requestTaskActionType:
    | 'RFI_SUBMIT'
    | 'RFI_UPLOAD_ATTACHMENT'
    | 'RFI_RESPONSE_SUBMIT'
    | 'RFI_CANCEL'
    | 'RDE_SUBMIT'
    | 'RDE_RESPONSE_SUBMIT'
    | 'RDE_FORCE_DECISION'
    | 'RDE_UPLOAD_ATTACHMENT'
    | 'PAYMENT_MARK_AS_PAID'
    | 'PAYMENT_MARK_AS_RECEIVED'
    | 'PAYMENT_PAY_BY_CARD'
    | 'PAYMENT_CANCEL';
}
