/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestedDocuments {
  auditMaterialReceivedDate: string;
  manufacturingProcessFile?: string;
  processFlowMapsFile?: string;
  annotatedSitePlansFile?: string;
  eligibleProcessFile?: string;
  directlyAssociatedActivitiesFile?: string;
  seventyPerCentRuleEvidenceFile?: string;
  baseYearTargetPeriodEvidenceFiles?: string[];
  additionalDocuments?: string[];
  additionalInformation?: string;
}
