/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestActionPayload {
  payloadType?:
    | 'RFI_SUBMITTED_PAYLOAD'
    | 'RFI_RESPONSE_SUBMITTED_PAYLOAD'
    | 'RDE_SUBMITTED_PAYLOAD'
    | 'RDE_REJECTED_PAYLOAD'
    | 'RDE_DECISION_FORCED_PAYLOAD'
    | 'PAYMENT_MARKED_AS_PAID_PAYLOAD'
    | 'PAYMENT_MARKED_AS_RECEIVED_PAYLOAD'
    | 'PAYMENT_COMPLETED_PAYLOAD'
    | 'PAYMENT_CANCELLED_PAYLOAD';
}
