/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTaskPayload } from './requestTaskPayload';
import { RfiQuestionPayload } from './rfiQuestionPayload';
import { RfiResponsePayload } from './rfiResponsePayload';

export interface RfiResponseSubmitRequestTaskPayload extends RequestTaskPayload {
  rfiQuestionPayload: RfiQuestionPayload;
  rfiResponsePayload: RfiResponsePayload;
  rfiAttachments?: { [key: string]: string };
}
