/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

export interface SectorAssociationContactDTO {
  title?: string;
  firstName: string;
  lastName: string;
  jobTitle?: string;
  organisationName?: string;
  address: AddressDTO;
  phoneNumber?: string;
  email: string;
  fullName?: string;
}
