/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorAssociationSchemeDocumentDTO } from './sectorAssociationSchemeDocumentDTO';
import { SubsectorAssociationSchemeInfoDTO } from './subsectorAssociationSchemeInfoDTO';
import { TargetSetDTO } from './targetSetDTO';

export interface SectorAssociationSchemeDTO {
  id: number;
  umbrellaAgreement: SectorAssociationSchemeDocumentDTO;
  targetSet?: TargetSetDTO;
  umaDate?: string;
  sectorDefinition?: string;
  subsectorAssociationSchemes?: Array<SubsectorAssociationSchemeInfoDTO>;
}
