/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorUserAuthorityUpdateDTO } from './sectorUserAuthorityUpdateDTO';

/**
 * The sector user authority to update
 */
export interface SectorUserAuthorityUpdateWrapperDTO {
  sectorUserAuthorityUpdateDTOList: SectorUserAuthorityUpdateDTO[];
}
