/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorAssociationContactDTO } from './sectorAssociationContactDTO';
import { SectorAssociationDetailsResponseDTO } from './sectorAssociationDetailsResponseDTO';

export interface SectorAssociationResponseDTO {
  sectorAssociationContact: SectorAssociationContactDTO;
  sectorAssociationDetails: SectorAssociationDetailsResponseDTO;
  editable?: boolean;
}
