/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorAssociationSiteContactInfoDTO } from './sectorAssociationSiteContactInfoDTO';

export interface SectorAssociationSiteContactInfoResponse {
  siteContacts?: SectorAssociationSiteContactInfoDTO[];
  editable?: boolean;
  totalItems?: number;
}
