/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneNumberDTO } from './phoneNumberDTO';

/**
 * The sector user
 */
export interface SectorUserRegistrationWithCredentialsDTO {
  emailToken: string;
  firstName: string;
  lastName: string;
  jobTitle?: string;
  contactType?: 'SECTOR_ASSOCIATION' | 'OPERATOR' | 'CONSULTANT';
  organisationName?: string;
  phoneNumber?: PhoneNumberDTO;
  mobileNumber?: PhoneNumberDTO;
  password: string;
}
