/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The search criteria
 */
export interface SectorAccountPerformanceDataReportSearchCriteria {
  accountId?: number;
  targetUnitAccountBusinessId?: string;
  targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9';
  performanceOutcome?:
    'TARGET_MET' | 'BUY_OUT_REQUIRED' | 'SURPLUS_USED_BUY_OUT_REQUIRED' | 'SURPLUS_USED' | 'OUTSTANDING';
  submissionType?: 'PRIMARY' | 'SECONDARY';
  pageNumber: number;
  pageSize: number;
}
