/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The sector user sector association registration info
 */
export interface SectorUserInvitationDTO {
  email: string;
  firstName: string;
  lastName: string;
  roleCode?: string;
  contactType?: 'SECTOR_ASSOCIATION' | 'OPERATOR' | 'CONSULTANT';
}
