/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorAssociationSchemeDocumentDTO } from './sectorAssociationSchemeDocumentDTO';
import { TargetSetDTO } from './targetSetDTO';

export interface SectorAssociationSchemeDTO {
  id: number;
  umbrellaAgreement: SectorAssociationSchemeDocumentDTO;
  targetSet?: TargetSetDTO;
  umaDate?: string;
  sectorDefinition?: string;
  schemeVersion: 'CCA_2' | 'CCA_3';
  editable?: boolean;
}
