/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';

export interface SectorMoaGeneratedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  paymentRequestId: string;
  chargingYear: number;
  transactionId: string;
  moaDocument: FileInfoDTO;
  recipients: DefaultNoticeRecipient[];
}
