/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneNumberDTO } from './phoneNumberDTO';

export interface SectorUserDTO {
  email: string;
  firstName: string;
  lastName: string;
  status?: 'REGISTERED' | 'PENDING' | 'DELETED';
  jobTitle?: string;
  phoneNumber?: PhoneNumberDTO;
  mobileNumber?: PhoneNumberDTO;
}
