/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoaReport } from './moaReport';

export interface SubsistenceFeesRunRequestMetadata {
  type?: string;
  chargingYear?: number;
  sectorsReports?: Record<string, MoaReport>;
  accountsReports?: Record<string, MoaReport>;
  skippedSectors?: number;
  readonly sentInvoices?: number;
  readonly failedInvoices?: number;
}
