/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubsistenceFeesMoaReceivedAmountHistoryDTO } from './subsistenceFeesMoaReceivedAmountHistoryDTO';

export interface SubsistenceFeesMoaReceivedAmountInfoDTO {
  transactionId?: string;
  businessId?: string;
  name?: string;
  paymentStatus?: 'AWAITING_PAYMENT' | 'PAID' | 'CANCELLED' | 'OVERPAID';
  currentTotalAmount?: string;
  receivedAmount?: string;
  receivedAmountHistoryList?: SubsistenceFeesMoaReceivedAmountHistoryDTO[];
}
