/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubsistenceFeesRunCompletedRequestActionPayloadChargingYear } from './subsistenceFeesRunCompletedRequestActionPayloadChargingYear';
import { FileInfoDTO } from './fileInfoDTO';

export interface SubsistenceFeesRunCompletedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  paymentRequestId: string;
  chargingYear: SubsistenceFeesRunCompletedRequestActionPayloadChargingYear;
  status: string;
  sentInvoices: number;
  failedInvoices?: number;
  report?: FileInfoDTO;
}
