/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SubsistenceFeesMoaReceivedAmountHistoryDTO {
  id?: number;
  submitter?: string;
  submissionDate?: string;
  transactionAmount?: string;
  comments?: string;
  evidenceFiles?: Record<string, string>;
}
