/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The received amount details
 */
export interface SubsistenceFeesMoaReceivedAmountDetailsDTO {
  transactionAmount: string;
  comments?: string;
  evidenceFiles?: Record<string, string>;
}
