/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetSetDTO } from './targetSetDTO';

export interface SubsectorAssociationSchemeDTO {
  id: number;
  targetSet: TargetSetDTO;
  editable?: boolean;
}
