/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountAddressDTO } from './accountAddressDTO';
import { TargetUnitAccountContactDTO } from './targetUnitAccountContactDTO';

export interface TargetUnitAccountPayload {
  name: string;
  emissionTradingScheme: 'DUMMY_EMISSION_TRADING_SCHEME';
  competentAuthority: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  operatorType: 'LIMITED_COMPANY' | 'PARTNERSHIP' | 'SOLE_TRADER' | 'NONE';
  isCompanyRegistrationNumber: boolean;
  companyRegistrationNumber?: string;
  registrationNumberMissingReason?: string;
  sicCode?: string;
  subsectorAssociationId?: number;
  address: AccountAddressDTO;
  responsiblePerson: TargetUnitAccountContactDTO;
  administrativeContactDetails: TargetUnitAccountContactDTO;
}
