/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { PerformanceDataCalculatedMetrics } from './performanceDataCalculatedMetrics';

export interface TargetUnitAccountUploadReport {
  accountId?: number;
  accountBusinessId?: string;
  file?: FileInfoDTO;
  succeeded?: boolean;
  performanceDataCalculatedMetrics?: PerformanceDataCalculatedMetrics;
  errors?: string[];
}
