/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetUnitAccountInfoDTO } from './targetUnitAccountInfoDTO';

export interface TargetUnitAccountInfoResponseDTO {
  accountsWithSiteContact?: TargetUnitAccountInfoDTO[];
  editable?: boolean;
  totalItems?: number;
}
