/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubsectorAssociationDTO } from './subsectorAssociationDTO';
import { TargetUnitAccountDetailsDTO } from './targetUnitAccountDetailsDTO';
import { UnderlyingAgreementDetailsDTO } from './underlyingAgreementDetailsDTO';

export interface TargetUnitAccountDetailsResponseDTO {
  targetUnitAccountDetails?: TargetUnitAccountDetailsDTO;
  subsectorAssociation?: SubsectorAssociationDTO;
  underlyingAgreementDetails?: UnderlyingAgreementDetailsDTO;
}
