/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TargetCommitmentDTO {
  id?: number;
  targetPeriod: string;
  targetImprovement?: string;
}
