/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TargetPeriodPerformanceResult {
  targetEnergyCarbonTpThroughput?: string;
  byEnergyCarbonTpThroughput?: string;
  tpPerformance: string;
  tpPerformancePercent: string;
  tpOutcome: 'TARGET_MET' | 'BUY_OUT_REQUIRED' | 'SURPLUS_USED_BUY_OUT_REQUIRED' | 'SURPLUS_USED' | 'OUTSTANDING';
}
