/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountAddressDTO } from './accountAddressDTO';
import { PhoneNumberDTO } from './phoneNumberDTO';

export interface TargetUnitAccountContactDTO {
  email: string;
  firstName: string;
  lastName: string;
  jobTitle?: string;
  address: AccountAddressDTO;
  phoneNumber?: PhoneNumberDTO;
}
