/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetUnitAccountContactDTO } from './targetUnitAccountContactDTO';
import { AccountAddressDTO } from './accountAddressDTO';

export interface TargetUnitAccountDetails {
  operatorName?: string;
  operatorType?: 'LIMITED_COMPANY' | 'PARTNERSHIP' | 'SOLE_TRADER' | 'NONE';
  companyRegistrationNumber?: string;
  registrationNumberMissingReason?: string;
  address?: AccountAddressDTO;
  responsiblePerson?: TargetUnitAccountContactDTO;
  administrativeContactDetails?: TargetUnitAccountContactDTO;
  sectorAssociationId?: number;
  subsectorAssociationId?: number;
}
