/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountAddressDTO } from './accountAddressDTO';
import { TargetUnitAccountContactDTO } from './targetUnitAccountContactDTO';

export interface TargetUnitAccountDetails {
  operatorName?: string;
  operatorType?: 'LIMITED_COMPANY' | 'PARTNERSHIP' | 'SOLE_TRADER' | 'NONE';
  companyRegistrationNumber?: string;
  registrationNumberMissingReason?: string;
  address?: AccountAddressDTO;
  responsiblePerson?: TargetUnitAccountContactDTO;
  administrativeContactDetails?: TargetUnitAccountContactDTO;
  sectorAssociationId?: number;
  subsectorAssociationId?: number;
}
