/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyOutCalculatedDetails } from './buyOutCalculatedDetails';
import { BuyOutSurplusDetails } from './buyOutSurplusDetails';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';

export interface TP6BuyOutCalculatedAccountProcessingSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  details: BuyOutSurplusDetails;
  defaultContacts?: DefaultNoticeRecipient[];
  buyOutCalculatedDetails: BuyOutCalculatedDetails;
}
