/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActualTargetPeriodPerformance } from './actualTargetPeriodPerformance';
import { PrimaryDetermination } from './primaryDetermination';
import { SecondaryDetermination } from './secondaryDetermination';
import { TargetPeriodPerformanceResult } from './targetPeriodPerformanceResult';
import { PerformanceDataTargetUnitDetails } from './performanceDataTargetUnitDetails';

export interface TP6PerformanceDataAllOf {
  targetUnitDetails?: PerformanceDataTargetUnitDetails;
  actualTargetPeriodPerformance?: ActualTargetPeriodPerformance;
  performanceResult?: TargetPeriodPerformanceResult;
  primaryDetermination?: PrimaryDetermination;
  secondaryDetermination?: SecondaryDetermination;
}
