/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyOutSurplusDetails } from './buyOutSurplusDetails';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { SurplusCalculatedDetails } from './surplusCalculatedDetails';

export interface TP6SurplusCalculatedAccountProcessingSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  details: BuyOutSurplusDetails;
  defaultContacts?: DefaultNoticeRecipient[];
  surplusCalculatedDetails: SurplusCalculatedDetails;
}
