/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Determination } from './determination';
import { UnderlyingAgreementFacilityReviewDecision } from './underlyingAgreementFacilityReviewDecision';

export interface UnderlyingAgreementSaveFacilityReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  determination?: Determination;
  group: string;
  decision: UnderlyingAgreementFacilityReviewDecision;
  reviewSectionsCompleted?: Record<string, string>;
}
