/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorisationAndAdditionalEvidence } from './authorisationAndAdditionalEvidence';
import { FacilityItem } from './facilityItem';
import { UnderlyingAgreementTargetUnitDetails } from './underlyingAgreementTargetUnitDetails';

export interface UnderlyingAgreementApplySavePayload {
  underlyingAgreementTargetUnitDetails: UnderlyingAgreementTargetUnitDetails;
  facilities: FacilityItem[];
  authorisationAndAdditionalEvidence: AuthorisationAndAdditionalEvidence;
}
