/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementActivationDetails } from './underlyingAgreementActivationDetails';

export interface UnderlyingAgreementVariationActivationRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  underlyingAgreementActivationDetails?: UnderlyingAgreementActivationDetails;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementActivationAttachments?: Record<string, string>;
}
