/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { AccountReferenceData } from './accountReferenceData';
import { VariationRegulatorLedDetermination } from './variationRegulatorLedDetermination';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { FileInfoDTO } from './fileInfoDTO';

export interface UnderlyingAgreementVariationRegulatorLedCompletedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  facilityChargeStartDateMap?: Record<string, string>;
  determination: VariationRegulatorLedDetermination;
  decisionNotification: CcaDecisionNotification;
  defaultContacts: DefaultNoticeRecipient[];
  usersInfo?: Record<string, RequestActionUserInfo>;
  underlyingAgreementDocuments?: Record<string, FileInfoDTO>;
  officialNotices: FileInfoDTO[];
  regulatorLedSubmitAttachments?: Record<string, string>;
}
