/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { UnderlyingAgreementContainer } from './underlyingAgreementContainer';
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';

export interface UnderlyingAgreementVariationSubmitRequestTaskPayload {
  payloadType?: string;
  accountReferenceData?: AccountReferenceData;
  originalUnderlyingAgreementContainer?: UnderlyingAgreementContainer;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: { [key: string]: string };
  underlyingAgreementAttachments?: { [key: string]: string };
}
