/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Facility } from './facility';
import { SchemeData } from './schemeData';
import { UnderlyingAgreement } from './underlyingAgreement';

export interface UnderlyingAgreementContainer {
  schemeDataMap: Record<string, SchemeData>;
  underlyingAgreement: UnderlyingAgreement;
  excludedFacilities?: Facility[];
  underlyingAgreementAttachments?: Record<string, string>;
}
