/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Determination } from './determination';

export interface UnderlyingAgreementSaveReviewDeterminationRequestTaskActionPayload {
  payloadType?: string;
  determination?: Determination;
  reviewSectionsCompleted?: Record<string, string>;
}
