/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Determination } from './determination';
import { UnderlyingAgreementApplySavePayload } from './underlyingAgreementApplySavePayload';

export interface UnderlyingAgreementSaveReviewRequestTaskActionPayload {
  payloadType?: string;
  determination?: Determination;
  underlyingAgreement?: UnderlyingAgreementApplySavePayload;
  sectionsCompleted?: Record<string, string>;
  reviewSectionsCompleted?: Record<string, string>;
}
