/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { UnderlyingAgreementPayload } from './underlyingAgreementPayload';

export interface UnderlyingAgreementSubmittedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement: UnderlyingAgreementPayload;
  underlyingAgreementAttachments?: Record<string, string>;
}
