/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { Determination } from './determination';

export interface UnderlyingAgreementSaveReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  determination?: Determination;
  group:
    | 'TARGET_UNIT_DETAILS'
    | 'TARGET_PERIOD5_DETAILS'
    | 'TARGET_PERIOD6_DETAILS'
    | 'AUTHORISATION_AND_ADDITIONAL_EVIDENCE';
  decision: UnderlyingAgreementReviewDecision;
  reviewSectionsCompleted?: Record<string, string>;
}
