/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementVariationRegulatorLedSavePayload } from './underlyingAgreementVariationRegulatorLedSavePayload';
import { VariationRegulatorLedDetermination } from './variationRegulatorLedDetermination';

export interface UnderlyingAgreementVariationRegulatorLedSaveRequestTaskActionPayload {
  payloadType?: string;
  underlyingAgreement?: UnderlyingAgreementVariationRegulatorLedSavePayload;
  determination?: VariationRegulatorLedDetermination;
  sectionsCompleted?: Record<string, string>;
}
