/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementApplySavePayload } from './underlyingAgreementApplySavePayload';

export interface UnderlyingAgreementSaveRequestTaskActionPayload {
  payloadType?: string;
  underlyingAgreement?: UnderlyingAgreementApplySavePayload;
  sectionsCompleted?: Record<string, string>;
}
