/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { UnderlyingAgreementVariationFacilityReviewDecision } from './underlyingAgreementVariationFacilityReviewDecision';
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';
import { VariationDetermination } from './variationDetermination';

export interface UnderlyingAgreementVariationRejectedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  decisionNotification: CcaDecisionNotification;
  defaultContacts: DefaultNoticeRecipient[];
  usersInfo?: Record<string, RequestActionUserInfo>;
  officialNotices: FileInfoDTO[];
  determination: VariationDetermination;
  reviewSectionsCompleted?: Record<string, string>;
  reviewGroupDecisions?: Record<string, UnderlyingAgreementReviewDecision>;
  facilitiesReviewGroupDecisions?: Record<string, UnderlyingAgreementVariationFacilityReviewDecision>;
  reviewAttachments?: Record<string, string>;
}
