/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementFacilityReviewDecision } from './underlyingAgreementFacilityReviewDecision';
import { CcaPeerReviewDecision } from './ccaPeerReviewDecision';
import { AccountReferenceData } from './accountReferenceData';
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { Determination } from './determination';
import { UnderlyingAgreementPayload } from './underlyingAgreementPayload';

export interface UnderlyingAgreementPeerReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  workflowSchemeVersion?: 'CCA_2' | 'CCA_3';
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement?: UnderlyingAgreementPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  underlyingAgreementProposed?: UnderlyingAgreementPayload;
  reviewSectionsCompleted?: Record<string, string>;
  reviewGroupDecisions?: Record<string, UnderlyingAgreementReviewDecision>;
  facilitiesReviewGroupDecisions?: Record<string, UnderlyingAgreementFacilityReviewDecision>;
  reviewAttachments?: Record<string, string>;
  determination?: Determination;
  decision?: CcaPeerReviewDecision;
  peerReviewAttachments?: Record<string, string>;
}
