/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { UnderlyingAgreementPayload } from './underlyingAgreementPayload';

export interface UnderlyingAgreementNotifyOperatorForDecisionRequestTaskActionPayload {
  payloadType?: string;
  decisionNotification: CcaDecisionNotification;
  underlyingAgreementProposed: UnderlyingAgreementPayload;
}
