/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { UnderlyingAgreementVariationFacilityReviewDecision } from './underlyingAgreementVariationFacilityReviewDecision';
import { UnderlyingAgreementVariationReviewSavePayload } from './underlyingAgreementVariationReviewSavePayload';
import { VariationDetermination } from './variationDetermination';

export interface UnderlyingAgreementVariationSaveReviewRequestTaskActionPayload {
  payloadType?: string;
  underlyingAgreement?: UnderlyingAgreementVariationReviewSavePayload;
  determination?: VariationDetermination;
  reviewGroupDecisions?: Record<string, UnderlyingAgreementReviewDecision>;
  facilitiesReviewGroupDecisions?: Record<string, UnderlyingAgreementVariationFacilityReviewDecision>;
  sectionsCompleted?: Record<string, string>;
  reviewSectionsCompleted?: Record<string, string>;
}
