/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';
import { AccountReferenceData } from './accountReferenceData';
import { VariationRegulatorLedDetermination } from './variationRegulatorLedDetermination';
import { UnderlyingAgreementContainer } from './underlyingAgreementContainer';

export interface UnderlyingAgreementVariationRegulatorLedSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  workflowSchemeVersion?: 'CCA_2' | 'CCA_3';
  accountReferenceData?: AccountReferenceData;
  originalUnderlyingAgreementContainer?: UnderlyingAgreementContainer;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  facilityChargeStartDateMap?: Record<string, string>;
  determination?: VariationRegulatorLedDetermination;
  regulatorLedSubmitAttachments?: Record<string, string>;
}
