/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { UnderlyingAgreementActivationDetails } from './underlyingAgreementActivationDetails';

export interface UnderlyingAgreementActivatedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  accountReferenceData?: AccountReferenceData;
  decisionNotification: CcaDecisionNotification;
  defaultContacts: DefaultNoticeRecipient[];
  usersInfo?: Record<string, RequestActionUserInfo>;
  officialNotice: FileInfoDTO;
  underlyingAgreementDocuments: Record<string, FileInfoDTO>;
  underlyingAgreementActivationDetails: UnderlyingAgreementActivationDetails;
  underlyingAgreementActivationAttachments?: Record<string, string>;
}
