/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { CcaDecisionNotification } from './ccaDecisionNotification';
import { DefaultNoticeRecipient } from './defaultNoticeRecipient';
import { Determination } from './determination';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { UnderlyingAgreementVariationFacilityReviewDecision } from './underlyingAgreementVariationFacilityReviewDecision';
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';

export interface UnderlyingAgreementVariationAcceptedRequestActionPayload {
  payloadType?: string;
  businessId?: string;
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: { [key: string]: string };
  underlyingAgreementAttachments?: { [key: string]: string };
  decisionNotification: CcaDecisionNotification;
  defaultContacts: Array<DefaultNoticeRecipient>;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
  determination: Determination;
  reviewSectionsCompleted?: { [key: string]: string };
  reviewGroupDecisions?: { [key: string]: UnderlyingAgreementReviewDecision };
  facilitiesReviewGroupDecisions?: { [key: string]: UnderlyingAgreementVariationFacilityReviewDecision };
  reviewAttachments?: { [key: string]: string };
  underlyingAgreementDocument: FileInfoDTO;
}
