/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { UnderlyingAgreementVariationApplySavePayload } from './underlyingAgreementVariationApplySavePayload';
import { UnderlyingAgreementVariationFacilityReviewDecision } from './underlyingAgreementVariationFacilityReviewDecision';

export interface UnderlyingAgreementVariationSaveRequestTaskActionPayload {
  payloadType?: string;
  underlyingAgreement?: UnderlyingAgreementVariationApplySavePayload;
  sectionsCompleted?: Record<string, string>;
  reviewGroupDecisions?: Record<string, UnderlyingAgreementReviewDecision>;
  facilitiesReviewGroupDecisions?: Record<string, UnderlyingAgreementVariationFacilityReviewDecision>;
  reviewSectionsCompleted?: Record<string, string>;
}
