/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { UnderlyingAgreementPayload } from './underlyingAgreementPayload';

export interface UnderlyingAgreementSubmitRequestTaskPayload {
  payloadType?: string;
  accountReferenceData?: AccountReferenceData;
  underlyingAgreement?: UnderlyingAgreementPayload;
  sectionsCompleted?: { [key: string]: string };
  underlyingAgreementAttachments?: { [key: string]: string };
}
