/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { CcaPeerReviewDecision } from './ccaPeerReviewDecision';
import { UnderlyingAgreementContainer } from './underlyingAgreementContainer';
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';
import { VariationRegulatorLedDetermination } from './variationRegulatorLedDetermination';

export interface UnderlyingAgreementVariationRegulatorLedPeerReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  workflowSchemeVersion?: 'CCA_2' | 'CCA_3';
  accountReferenceData?: AccountReferenceData;
  originalUnderlyingAgreementContainer?: UnderlyingAgreementContainer;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  facilityChargeStartDateMap?: Record<string, string>;
  determination?: VariationRegulatorLedDetermination;
  regulatorLedSubmitAttachments?: Record<string, string>;
  decision?: CcaPeerReviewDecision;
  peerReviewAttachments?: Record<string, string>;
}
