/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnderlyingAgreementReviewDecisionDetails } from './underlyingAgreementReviewDecisionDetails';

export interface UnderlyingAgreementFacilityReviewDecision {
  type: 'ACCEPTED' | 'REJECTED';
  details?: UnderlyingAgreementReviewDecisionDetails;
  changeStartDate?: boolean;
  startDate?: string;
}
