/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReferenceData } from './accountReferenceData';
import { UnderlyingAgreementContainer } from './underlyingAgreementContainer';
import { UnderlyingAgreementReviewDecision } from './underlyingAgreementReviewDecision';
import { UnderlyingAgreementVariationFacilityReviewDecision } from './underlyingAgreementVariationFacilityReviewDecision';
import { UnderlyingAgreementVariationPayload } from './underlyingAgreementVariationPayload';

export interface UnderlyingAgreementVariationSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  workflowSchemeVersion?: 'CCA_2' | 'CCA_3';
  accountReferenceData?: AccountReferenceData;
  originalUnderlyingAgreementContainer?: UnderlyingAgreementContainer;
  underlyingAgreement?: UnderlyingAgreementVariationPayload;
  sectionsCompleted?: Record<string, string>;
  underlyingAgreementAttachments?: Record<string, string>;
  reviewSectionsCompleted?: Record<string, string>;
  reviewGroupDecisions?: Record<string, UnderlyingAgreementReviewDecision>;
  facilitiesReviewGroupDecisions?: Record<string, UnderlyingAgreementVariationFacilityReviewDecision>;
}
