/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

export interface VerificationBodyDTO {
  id?: number;
  name?: string;
  accreditationReferenceNumber?: string;
  status?: 'ACTIVE' | 'PENDING' | 'DISABLED';
  address?: AddressDTO;
  emissionTradingSchemes?: Array<'DUMMY_EMISSION_TRADING_SCHEME' | 'DUMMY_EMISSION_TRADING_SCHEME_2'>;
}
