/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-netz-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

/**
 * The verification body dto to update
 */
export interface VerificationBodyUpdateDTO {
  id: number;
  name: string;
  accreditationReferenceNumber: string;
  address: AddressDTO;
  emissionTradingSchemes: Array<'DUMMY_EMISSION_TRADING_SCHEME' | 'DUMMY_EMISSION_TRADING_SCHEME_2'>;
}
