package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMIT = "UNDERLYING_AGREEMENT_APPLICATION_SUBMIT";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_WAIT_FOR_REVIEW = "UNDERLYING_AGREEMENT_WAIT_FOR_REVIEW";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION";
    public static final String UNDERLYING_AGREEMENT_WAIT_FOR_ACTIVATION = "UNDERLYING_AGREEMENT_WAIT_FOR_ACTIVATION";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW";
    public static final String UNDERLYING_AGREEMENT_WAIT_FOR_PEER_REVIEW = "UNDERLYING_AGREEMENT_WAIT_FOR_PEER_REVIEW";

    // Admin Termination
    public static final String ADMIN_TERMINATION_APPLICATION_SUBMIT = "ADMIN_TERMINATION_APPLICATION_SUBMIT";
    public static final String ADMIN_TERMINATION_APPLICATION_WITHDRAW = "ADMIN_TERMINATION_APPLICATION_WITHDRAW";
    public static final String ADMIN_TERMINATION_APPLICATION_FINAL_DECISION = "ADMIN_TERMINATION_APPLICATION_FINAL_DECISION";
    public static final String ADMIN_TERMINATION_APPLICATION_PEER_REVIEW = "ADMIN_TERMINATION_APPLICATION_PEER_REVIEW";
    public static final String ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW = "ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_ACTIVATION = "UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_ACTIVATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_PEER_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_WAIT_FOR_PEER_REVIEW";

    // Performance data download
    public static final String PERFORMANCE_DATA_DOWNLOAD_SUBMIT = "PERFORMANCE_DATA_DOWNLOAD_SUBMIT";

    // Performance data upload
    public static final String PERFORMANCE_DATA_UPLOAD_SUBMIT = "PERFORMANCE_DATA_UPLOAD_SUBMIT";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT";
}
