package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestPayloadType {

    public static final String TARGET_UNIT_ACCOUNT_CREATION_REQUEST_PAYLOAD = "TARGET_UNIT_ACCOUNT_CREATION_REQUEST_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_REQUEST_PAYLOAD = "UNDERLYING_AGREEMENT_REQUEST_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REQUEST_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REQUEST_PAYLOAD";
    public static final String ADMIN_TERMINATION_REQUEST_PAYLOAD = "ADMIN_TERMINATION_REQUEST_PAYLOAD";
    public static final String PERFORMANCE_DATA_DOWNLOAD_PAYLOAD = "PERFORMANCE_DATA_DOWNLOAD_PAYLOAD";
    public static final String PERFORMANCE_DATA_GENERATE_PAYLOAD = "PERFORMANCE_DATA_GENERATE_PAYLOAD";
    public static final String PERFORMANCE_DATA_SPREADSHEET_GENERATE_PAYLOAD = "PERFORMANCE_DATA_SPREADSHEET_GENERATE_PAYLOAD";
    public static final String PERFORMANCE_DATA_UPLOAD_PAYLOAD = "PERFORMANCE_DATA_UPLOAD_PAYLOAD";
    public static final String PERFORMANCE_DATA_PROCESSING_PAYLOAD = "PERFORMANCE_DATA_PROCESSING_PAYLOAD";
    public static final String PERFORMANCE_DATA_SPREADSHEET_PROCESSING_PAYLOAD = "PERFORMANCE_DATA_SPREADSHEET_PROCESSING_PAYLOAD";
    
    public static final String PERFORMANCE_ACCCOUNT_TEMPLATE_DATA_UPLOAD_PAYLOAD = "PERFORMANCE_ACCCOUNT_TEMPLATE_DATA_UPLOAD_PAYLOAD";
    public static final String PERFORMANCE_ACCCOUNT_TEMPLATE_DATA_PROCESSING_PAYLOAD = "PERFORMANCE_ACCCOUNT_TEMPLATE_DATA_PROCESSING_PAYLOAD";
    
    public static final String SUBSISTENCE_FEES_RUN_REQUEST_PAYLOAD = "SUBSISTENCE_FEES_RUN_REQUEST_PAYLOAD";
    public static final String SECTOR_MOA_REQUEST_PAYLOAD = "SECTOR_MOA_REQUEST_PAYLOAD";
    public static final String TARGET_UNIT_MOA_REQUEST_PAYLOAD = "TARGET_UNIT_MOA_REQUEST_PAYLOAD";

    public static final String BUY_OUT_SURPLUS_RUN_REQUEST_PAYLOAD = "BUY_OUT_SURPLUS_RUN_REQUEST_PAYLOAD";
    public static final String BUY_OUT_SURPLUS_ACCOUNT_PROCESSING_PAYLOAD = "BUY_OUT_SURPLUS_ACCOUNT_PROCESSING_PAYLOAD";
}
