package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskActionType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_SUBMIT_APPLICATION = "UNDERLYING_AGREEMENT_SUBMIT_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_UPLOAD_SECTION_ATTACHMENT = "UNDERLYING_AGREEMENT_UPLOAD_SECTION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_CANCEL_APPLICATION = "UNDERLYING_AGREEMENT_CANCEL_APPLICATION";
    
    public static final String UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "UNDERLYING_AGREEMENT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION = "UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION";
    public static final String UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION";
   
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_ACTIVATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_UPLOAD_ATTACHMENT = "UNDERLYING_AGREEMENT_ACTIVATION_UPLOAD_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SAVE_APPLICATION = "ADMIN_TERMINATION_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_UPLOAD_ATTACHMENT = "ADMIN_TERMINATION_UPLOAD_ATTACHMENT";
    public static final String ADMIN_TERMINATION_CANCEL_APPLICATION = "ADMIN_TERMINATION_CANCEL_APPLICATION";
    public static final String ADMIN_TERMINATION_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String ADMIN_TERMINATION_WITHDRAW_SAVE_APPLICATION = "ADMIN_TERMINATION_WITHDRAW_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_WITHDRAW_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_WITHDRAW_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String ADMIN_TERMINATION_FINAL_DECISION_SAVE_APPLICATION = "ADMIN_TERMINATION_FINAL_DECISION_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_FINAL_DECISION_NOTIFY_OPERATOR_FOR_DECISION";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_UPLOAD_SECTION_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_UPLOAD_SECTION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_UPLOAD_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_UPLOAD_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION";


}
