package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskActionPayloadType {

    // Common
    public static final String NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SAVE_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_SAVE_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION_PAYLOAD = "UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_SAVE_PAYLOAD = "UNDERLYING_AGREEMENT_ACTIVATION_SAVE_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SAVE_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SAVE_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SAVE_PAYLOAD = "ADMIN_TERMINATION_SAVE_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_SAVE_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_SAVE_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_SAVE_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_SAVE_PAYLOAD";

    // Performance data download
    public static final String PERFORMANCE_DATA_DOWNLOAD_GENERATE_PAYLOAD = "PERFORMANCE_DATA_DOWNLOAD_GENERATE_PAYLOAD";

    // Performance data upload
    public static final String PERFORMANCE_DATA_UPLOAD_PROCESSING_PAYLOAD = "PERFORMANCE_DATA_UPLOAD_PROCESSING_PAYLOAD";
    
    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_PROCESSING_PAYLOAD = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_PROCESSING_PAYLOAD";
}
