package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskActionType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_SUBMIT_APPLICATION = "UNDERLYING_AGREEMENT_SUBMIT_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_UPLOAD_SECTION_ATTACHMENT = "UNDERLYING_AGREEMENT_UPLOAD_SECTION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_CANCEL_APPLICATION = "UNDERLYING_AGREEMENT_CANCEL_APPLICATION";

    public static final String UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_SAVE_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_SAVE_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_SAVE_FACILITY_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "UNDERLYING_AGREEMENT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION = "UNDERLYING_AGREEMENT_SAVE_REVIEW_DETERMINATION";
    public static final String UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String UNDERLYING_AGREEMENT_ACTIVATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_ACTIVATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_UPLOAD_ATTACHMENT = "UNDERLYING_AGREEMENT_ACTIVATION_UPLOAD_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String UNDERLYING_AGREEMENT_REQUEST_PEER_REVIEW = "UNDERLYING_AGREEMENT_REQUEST_PEER_REVIEW";
    public static final String UNDERLYING_AGREEMENT_SUBMIT_PEER_REVIEW_DECISION = "UNDERLYING_AGREEMENT_SUBMIT_PEER_REVIEW_DECISION";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SAVE_APPLICATION = "ADMIN_TERMINATION_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_UPLOAD_ATTACHMENT = "ADMIN_TERMINATION_UPLOAD_ATTACHMENT";
    public static final String ADMIN_TERMINATION_CANCEL_APPLICATION = "ADMIN_TERMINATION_CANCEL_APPLICATION";
    public static final String ADMIN_TERMINATION_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String ADMIN_TERMINATION_WITHDRAW_SAVE_APPLICATION = "ADMIN_TERMINATION_WITHDRAW_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_WITHDRAW_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_WITHDRAW_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String ADMIN_TERMINATION_FINAL_DECISION_SAVE_APPLICATION = "ADMIN_TERMINATION_FINAL_DECISION_SAVE_APPLICATION";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_NOTIFY_OPERATOR_FOR_DECISION = "ADMIN_TERMINATION_FINAL_DECISION_NOTIFY_OPERATOR_FOR_DECISION";

    public static final String ADMIN_TERMINATION_REQUEST_PEER_REVIEW = "ADMIN_TERMINATION_REQUEST_PEER_REVIEW";
    public static final String ADMIN_TERMINATION_SUBMIT_PEER_REVIEW_DECISION = "ADMIN_TERMINATION_SUBMIT_PEER_REVIEW_DECISION";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_UPLOAD_SECTION_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_UPLOAD_SECTION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_SAVE_APPLICATION_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_FACILITY_REVIEW_GROUP_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION = "UNDERLYING_AGREEMENT_VARIATION_SAVE_REVIEW_DETERMINATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_VARIATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_UPLOAD_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_UPLOAD_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REQUEST_PEER_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_REQUEST_PEER_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PEER_REVIEW_DECISION = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PEER_REVIEW_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SAVE_APPLICATION = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SAVE_APPLICATION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_UPLOAD_SECTION_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_UPLOAD_SECTION_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_UPLOAD_ATTACHMENT = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_UPLOAD_ATTACHMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_NOTIFY_OPERATOR_FOR_DECISION = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_REQUEST_PEER_REVIEW = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_REQUEST_PEER_REVIEW";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMIT_PEER_REVIEW_DECISION = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMIT_PEER_REVIEW_DECISION";

    // Performance data download
    public static final String PERFORMANCE_DATA_DOWNLOAD_GENERATE = "PERFORMANCE_DATA_DOWNLOAD_GENERATE";
    public static final String PERFORMANCE_DATA_DOWNLOAD_COMPLETE = "PERFORMANCE_DATA_DOWNLOAD_COMPLETE";

    // Performance data upload
    public static final String PERFORMANCE_DATA_UPLOAD_ATTACH_REPORT_PACKAGE = "PERFORMANCE_DATA_UPLOAD_ATTACH_REPORT_PACKAGE";
    public static final String PERFORMANCE_DATA_UPLOAD_PROCESSING = "PERFORMANCE_DATA_UPLOAD_PROCESSING";
    public static final String PERFORMANCE_DATA_UPLOAD_COMPLETE = "PERFORMANCE_DATA_UPLOAD_COMPLETE";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_ATTACH_REPORT_PACKAGE = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_ATTACH_REPORT_PACKAGE";
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_PROCESSING = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_PROCESSING";
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_COMPLETE = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_COMPLETE";

    // CCA3 Existing Facilities Migration
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_SAVE_APPLICATION = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_SAVE_APPLICATION";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_UPLOAD_ATTACHMENT = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_UPLOAD_ATTACHMENT";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_CANCEL_APPLICATION = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_CANCEL_APPLICATION";

    // Peer Review
    public static final String PEER_REVIEW_UPLOAD_ATTACHMENT = "PEER_REVIEW_UPLOAD_ATTACHMENT";

    // Facility Audit
    public static final String FACILITY_AUDIT_UPLOAD_ATTACHMENT = "FACILITY_AUDIT_UPLOAD_ATTACHMENT";
    public static final String FACILITY_AUDIT_CANCEL_APPLICATION = "FACILITY_AUDIT_CANCEL_APPLICATION";
    public static final String FACILITY_AUDIT_PRE_AUDIT_REVIEW_SAVE_APPLICATION = "FACILITY_AUDIT_PRE_AUDIT_REVIEW_SAVE_APPLICATION";
    public static final String FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMIT_APPLICATION = "FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMIT_APPLICATION";
    public static final String FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SAVE_APPLICATION = "FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SAVE_APPLICATION";
    public static final String FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMIT_APPLICATION = "FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMIT_APPLICATION";
    public static final String FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SAVE_RESPONSE = "FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SAVE_RESPONSE";
    public static final String FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMIT_RESPONSE = "FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMIT_RESPONSE";
    public static final String FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_COMPLETE_APPLICATION = "FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_COMPLETE_APPLICATION";

    // Non Compliance
    public static final String NON_COMPLIANCE_UPLOAD_ATTACHMENT = "NON_COMPLIANCE_UPLOAD_ATTACHMENT";
    public static final String NON_COMPLIANCE_CANCEL_APPLICATION = "NON_COMPLIANCE_CANCEL_APPLICATION";
    public static final String NON_COMPLIANCE_CLOSE_APPLICATION = "NON_COMPLIANCE_CLOSE_APPLICATION";
    public static final String NON_COMPLIANCE_DETAILS_SAVE_APPLICATION = "NON_COMPLIANCE_DETAILS_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_DETAILS_SUBMIT_APPLICATION = "NON_COMPLIANCE_DETAILS_SUBMIT_APPLICATION";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION = "NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR = "NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW = "NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW";


    // Performance Data Facility Digital Form
    public static final String PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SAVE_APPLICATION = "PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SAVE_APPLICATION";
    public static final String PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SUBMIT_APPLICATION = "PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SUBMIT_APPLICATION";
    public static final String PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_CANCEL_APPLICATION = "PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_CANCEL_APPLICATION";
    public static final String PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_REFRESH_APPLICATION = "PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_REFRESH_APPLICATION";
}
