package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestActionPayloadType {

    // Target Unit Account
    public static final String TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED_PAYLOAD = "TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED_PAYLOAD";

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_REJECTED_PAYLOAD = "UNDERLYING_AGREEMENT_REJECTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_ACCEPTED_PAYLOAD = "UNDERLYING_AGREEMENT_ACCEPTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_ACTIVATED_PAYLOAD = "UNDERLYING_AGREEMENT_ACTIVATED_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_SUBMITTED_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_SUBMITTED_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_SUBMITTED_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REJECTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REJECTED_PAYLOAD";
}
