package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestActionType {

    public static final String REQUEST_TERMINATED = "REQUEST_TERMINATED";

    // Target Unit Account
    public static final String TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED = "TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED";
    
    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMITTED = "UNDERLYING_AGREEMENT_APPLICATION_SUBMITTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_CANCELLED = "UNDERLYING_AGREEMENT_APPLICATION_CANCELLED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REJECTED = "UNDERLYING_AGREEMENT_APPLICATION_REJECTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACCEPTED = "UNDERLYING_AGREEMENT_APPLICATION_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATED = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_MIGRATED = "UNDERLYING_AGREEMENT_APPLICATION_MIGRATED";


    // Admin Termination
    public static final String ADMIN_TERMINATION_APPLICATION_CANCELLED = "ADMIN_TERMINATION_APPLICATION_CANCELLED";
    public static final String ADMIN_TERMINATION_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_APPLICATION_SUBMITTED";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_FINAL_DECISION_APPLICATION_SUBMITTED";
    public static final String ADMIN_TERMINATION_WITHDRAW_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_WITHDRAW_APPLICATION_SUBMITTED";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_CANCELLED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_CANCELLED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SUBMITTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SUBMITTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACCEPTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REJECTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REJECTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACTIVATED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACTIVATED";

    // Performance data upload
    public static final String PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED = "PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED";
    
    // Subsistence Fees
    public static final String SUBSISTENCE_FEES_RUN_SUBMITTED = "SUBSISTENCE_FEES_RUN_SUBMITTED";
    public static final String SUBSISTENCE_FEES_RUN_COMPLETED = "SUBSISTENCE_FEES_RUN_COMPLETED";
    public static final String SUBSISTENCE_FEES_RUN_COMPLETED_WITH_FAILURES = "SUBSISTENCE_FEES_RUN_COMPLETED_WITH_FAILURES";
    public static final String SECTOR_MOA_GENERATED = "SECTOR_MOA_GENERATED";
    public static final String TARGET_UNIT_MOA_GENERATED = "TARGET_UNIT_MOA_GENERATED";

    // Buy Out Surplus
    public static final String BUY_OUT_SURPLUS_RUN_SUBMITTED = "BUY_OUT_SURPLUS_RUN_SUBMITTED";
}
