package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestActionType {

    public static final String REQUEST_TERMINATED = "REQUEST_TERMINATED";

    // Target Unit Account
    public static final String TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED = "TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED";

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMITTED = "UNDERLYING_AGREEMENT_APPLICATION_SUBMITTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_CANCELLED = "UNDERLYING_AGREEMENT_APPLICATION_CANCELLED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REJECTED = "UNDERLYING_AGREEMENT_APPLICATION_REJECTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACCEPTED = "UNDERLYING_AGREEMENT_APPLICATION_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATED = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_MIGRATED = "UNDERLYING_AGREEMENT_APPLICATION_MIGRATED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_REQUESTED = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_REQUESTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEWER_ACCEPTED = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEWER_REJECTED = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEWER_REJECTED";


    // Admin Termination
    public static final String ADMIN_TERMINATION_APPLICATION_CANCELLED = "ADMIN_TERMINATION_APPLICATION_CANCELLED";
    public static final String ADMIN_TERMINATION_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_APPLICATION_SUBMITTED";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_FINAL_DECISION_APPLICATION_SUBMITTED";
    public static final String ADMIN_TERMINATION_WITHDRAW_APPLICATION_SUBMITTED = "ADMIN_TERMINATION_WITHDRAW_APPLICATION_SUBMITTED";
    public static final String ADMIN_TERMINATION_PEER_REVIEW_REQUESTED = "ADMIN_TERMINATION_PEER_REVIEW_REQUESTED";
    public static final String ADMIN_TERMINATION_APPLICATION_PEER_REVIEWER_ACCEPTED = "ADMIN_TERMINATION_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String ADMIN_TERMINATION_APPLICATION_PEER_REVIEWER_REJECTED = "ADMIN_TERMINATION_APPLICATION_PEER_REVIEWER_REJECTED";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_CANCELLED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_CANCELLED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SUBMITTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_SUBMITTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACCEPTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REJECTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REJECTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_COMPLETED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_COMPLETED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACTIVATED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_ACTIVATED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_REQUESTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_REQUESTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_SUBMITTED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_SUBMITTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_COMPLETED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_COMPLETED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW_REQUESTED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW_REQUESTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEWER_ACCEPTED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEWER_REJECTED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_ACTIVATED = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_ACTIVATED";

    // Performance data upload
    public static final String PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED = "PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING_SUBMITTED = "PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING_SUBMITTED";

    // Subsistence Fees
    public static final String SUBSISTENCE_FEES_RUN_SUBMITTED = "SUBSISTENCE_FEES_RUN_SUBMITTED";
    public static final String SUBSISTENCE_FEES_RUN_COMPLETED = "SUBSISTENCE_FEES_RUN_COMPLETED";
    public static final String SUBSISTENCE_FEES_RUN_COMPLETED_WITH_FAILURES = "SUBSISTENCE_FEES_RUN_COMPLETED_WITH_FAILURES";
    public static final String SECTOR_MOA_GENERATED = "SECTOR_MOA_GENERATED";
    public static final String TARGET_UNIT_MOA_GENERATED = "TARGET_UNIT_MOA_GENERATED";

    // Buy Out Surplus
    public static final String BUY_OUT_SURPLUS_RUN_SUBMITTED = "BUY_OUT_SURPLUS_RUN_SUBMITTED";
    public static final String BUY_OUT_SURPLUS_RUN_COMPLETED = "BUY_OUT_SURPLUS_RUN_COMPLETED";
    public static final String BUY_OUT_SURPLUS_RUN_COMPLETED_WITH_FAILURES = "BUY_OUT_SURPLUS_RUN_COMPLETED_WITH_FAILURES";
    public static final String TP6_BUY_OUT_ACCOUNT_PROCESSING_SUBMITTED = "TP6_BUY_OUT_ACCOUNT_PROCESSING_SUBMITTED";
    public static final String TP6_SURPLUS_ACCOUNT_PROCESSING_SUBMITTED = "TP6_SURPLUS_ACCOUNT_PROCESSING_SUBMITTED";

    // CCA3 Existing Facilities Migration
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_SUBMITTED = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_SUBMITTED";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_CANCELLED = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_CANCELLED";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATED = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATED";

    // Facility Audit
    public static final String FACILITY_AUDIT_CANCELLED = "FACILITY_AUDIT_CANCELLED";
    public static final String FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMITTED = "FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMITTED";
    public static final String FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMITTED = "FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMITTED";
    public static final String FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMITTED = "FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMITTED";

    // CCA2 Extension Notice
    public static final String CCA2_EXTENSION_NOTICE_ACCOUNT_PROCESSING_SUBMITTED = "CCA2_EXTENSION_NOTICE_ACCOUNT_PROCESSING_SUBMITTED";
    
    // CCA2 Termination
    public static final String CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED = "CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED";
    public static final String CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED_UNDERLYING_AGREEMENT_TERMINATED = "CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED_UNDERLYING_AGREEMENT_TERMINATED";

    // Non Compliance
    public static final String NON_COMPLIANCE_CANCELLED = "NON_COMPLIANCE_CANCELLED";
    public static final String NON_COMPLIANCE_CLOSED = "NON_COMPLIANCE_CLOSED";
    public static final String NON_COMPLIANCE_DETAILS_SUBMITTED = "NON_COMPLIANCE_DETAILS_SUBMITTED";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMITTED = "NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMITTED";

}
