package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestActionPayloadType {

    // Target Unit Account
    public static final String TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED_PAYLOAD = "TARGET_UNIT_ACCOUNT_CREATION_SUBMITTED_PAYLOAD";

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_REJECTED_PAYLOAD = "UNDERLYING_AGREEMENT_REJECTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_ACCEPTED_PAYLOAD = "UNDERLYING_AGREEMENT_ACCEPTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_ACTIVATED_PAYLOAD = "UNDERLYING_AGREEMENT_ACTIVATED_PAYLOAD";

    public static final String UNDERLYING_AGREEMENT_MIGRATED_PAYLOAD = "UNDERLYING_AGREEMENT_MIGRATED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_PEER_REVIEW_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_PEER_REVIEW_SUBMITTED_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_SUBMITTED_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_SUBMITTED_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_SUBMITTED_PAYLOAD";
    public static final String ADMIN_TERMINATION_PEER_REVIEW_SUBMITTED_PAYLOAD = "ADMIN_TERMINATION_PEER_REVIEW_SUBMITTED_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACCEPTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REJECTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REJECTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_COMPLETED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_COMPLETED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_PEER_REVIEW_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_PEER_REVIEW_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMITTED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_COMPLETED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_COMPLETED_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_PEER_REVIEW_SUBMITTED_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_PEER_REVIEW_SUBMITTED_PAYLOAD";

    // Performance data upload
    public static final String PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED_PAYLOAD = "PERFORMANCE_DATA_SPREADSHEET_PROCESSING_SUBMITTED_PAYLOAD";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING_SUBMITTED_PAYLOAD = "PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING_SUBMITTED_PAYLOAD";

    // Subsistence fees
    public static final String SUBSISTENCE_FEES_RUN_COMPLETED_PAYLOAD = "SUBSISTENCE_FEES_RUN_COMPLETED_PAYLOAD";
    public static final String SECTOR_MOA_GENERATED_PAYLOAD = "SECTOR_MOA_GENERATED_PAYLOAD";
    public static final String TARGET_UNIT_MOA_GENERATED_PAYLOAD = "TARGET_UNIT_MOA_GENERATED_PAYLOAD";

    // Buy Out Surplus
    public static final String BUY_OUT_SURPLUS_RUN_COMPLETED_PAYLOAD = "BUY_OUT_SURPLUS_RUN_COMPLETED_PAYLOAD";
    public static final String TP6_BUY_OUT_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD = "TP6_BUY_OUT_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD";
    public static final String TP6_SURPLUS_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD = "TP6_SURPLUS_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD";

    // CCA3 Existing Facilities Migration
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD";
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATED_PAYLOAD = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATED_PAYLOAD";

    // Facility Audit
    public static final String FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMITTED_PAYLOAD = "FACILITY_AUDIT_PRE_AUDIT_REVIEW_SUBMITTED_PAYLOAD";
    public static final String FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMITTED_PAYLOAD = "FACILITY_AUDIT_AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMITTED_PAYLOAD";
    public static final String FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMITTED_PAYLOAD = "FACILITY_AUDIT_TRACK_CORRECTIVE_ACTIONS_SUBMITTED_PAYLOAD";

    // CCA2 Extension Notice
    public static final String CCA2_EXTENSION_NOTICE_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD = "CCA2_EXTENSION_NOTICE_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD";

    // CCA2 Termination
    public static final String CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD = "CCA2_TERMINATION_ACCOUNT_PROCESSING_SUBMITTED_PAYLOAD";

    // Non Compliance
    public static final String NON_COMPLIANCE_DETAILS_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_DETAILS_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_CLOSED_PAYLOAD = "NON_COMPLIANCE_CLOSED_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMITTED_PAYLOAD";

}
