package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskPayloadType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SUBMIT_PAYLOAD = "ADMIN_TERMINATION_SUBMIT_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_PAYLOAD";
    public static final String ADMIN_TERMINATION_PEER_REVIEW_PAYLOAD = "ADMIN_TERMINATION_PEER_REVIEW_PAYLOAD";
    public static final String ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW_PAYLOAD";

    // Performance data download
    public static final String PERFORMANCE_DATA_DOWNLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_DATA_DOWNLOAD_SUBMIT_PAYLOAD";

    // Performance data upload
    public static final String PERFORMANCE_DATA_UPLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_DATA_UPLOAD_SUBMIT_PAYLOAD";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT_PAYLOAD";

    // CCA3 Existing Facilities Migration
    public static final String CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_PAYLOAD = "CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_PAYLOAD";

    // Facility Audit
    public static final String PRE_AUDIT_REVIEW_SUBMIT_PAYLOAD = "PRE_AUDIT_REVIEW_SUBMIT_PAYLOAD";
    public static final String AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMIT_PAYLOAD = "AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMIT_PAYLOAD";
    public static final String AUDIT_TRACK_CORRECTIVE_ACTIONS_PAYLOAD = "AUDIT_TRACK_CORRECTIVE_ACTIONS_PAYLOAD";

    // Non Compliance
    public static final String NON_COMPLIANCE_DETAILS_SUBMIT_PAYLOAD = "NON_COMPLIANT_DETAILS_SUBMIT_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PAYLOAD";
    public static final String NON_COMPLIANCE_ENFORCEMENT_RESPONSE_NOTICE_SUBMIT_PAYLOAD = "NON_COMPLIANCE_ENFORCEMENT_RESPONSE_NOTICE_SUBMIT_PAYLOAD";

    // Performance Data Facility Digital Form
    public static final String PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SUBMIT_PAYLOAD = "PERFORMANCE_DATA_FACILITY_DIGITAL_FORM_SUBMIT_PAYLOAD";
}
