package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskPayloadType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SUBMIT_PAYLOAD = "ADMIN_TERMINATION_SUBMIT_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD";

}
