package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestType {

    public static final String TARGET_UNIT_ACCOUNT_CREATION = "TARGET_UNIT_ACCOUNT_CREATION";
    public static final String UNDERLYING_AGREEMENT = "UNDERLYING_AGREEMENT";
    public static final String UNDERLYING_AGREEMENT_VARIATION = "UNDERLYING_AGREEMENT_VARIATION";
    public static final String ADMIN_TERMINATION = "ADMIN_TERMINATION";

    public static final String PERFORMANCE_DATA_DOWNLOAD = "PERFORMANCE_DATA_DOWNLOAD";
    public static final String PERFORMANCE_DATA_GENERATE = "PERFORMANCE_DATA_GENERATE";
    public static final String PERFORMANCE_DATA_SPREADSHEET_GENERATE = "PERFORMANCE_DATA_SPREADSHEET_GENERATE";

    public static final String PERFORMANCE_DATA_UPLOAD = "PERFORMANCE_DATA_UPLOAD";
    public static final String PERFORMANCE_DATA_PROCESSING = "PERFORMANCE_DATA_PROCESSING";
    public static final String PERFORMANCE_DATA_SPREADSHEET_PROCESSING = "PERFORMANCE_DATA_SPREADSHEET_PROCESSING";
    
    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD";
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_PROCESSING = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_PROCESSING";
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING = "PERFORMANCE_ACCOUNT_TEMPLATE_PROCESSING";
    
    public static final String SUBSISTENCE_FEES_RUN = "SUBSISTENCE_FEES_RUN";
    public static final String SECTOR_MOA = "SECTOR_MOA";
    public static final String TARGET_UNIT_MOA = "TARGET_UNIT_MOA";

    public static final String BUY_OUT_SURPLUS_RUN = "BUY_OUT_SURPLUS_RUN";
    public static final String BUY_OUT_SURPLUS_ACCOUNT_PROCESSING = "BUY_OUT_SURPLUS_ACCOUNT_PROCESSING";
}
