package uk.gov.cca.api.workflow.request.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class CcaRequestTaskPayloadType {

    // Underlying Agreement
    public static final String UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    // Admin Termination
    public static final String ADMIN_TERMINATION_SUBMIT_PAYLOAD = "ADMIN_TERMINATION_SUBMIT_PAYLOAD";
    public static final String ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD = "ADMIN_TERMINATION_FINAL_DECISION_PAYLOAD";
    public static final String ADMIN_TERMINATION_WITHDRAW_PAYLOAD = "ADMIN_TERMINATION_WITHDRAW_PAYLOAD";
    public static final String ADMIN_TERMINATION_PEER_REVIEW_PAYLOAD = "ADMIN_TERMINATION_PEER_REVIEW_PAYLOAD";
    public static final String ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "ADMIN_TERMINATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    // Underlying Agreement Variation
    public static final String UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_SUBMIT_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_ACTIVATION_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String UNDERLYING_AGREEMENT_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "UNDERLYING_AGREEMENT_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    // Performance data download
    public static final String PERFORMANCE_DATA_DOWNLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_DATA_DOWNLOAD_SUBMIT_PAYLOAD";

    // Performance data upload
    public static final String PERFORMANCE_DATA_UPLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_DATA_UPLOAD_SUBMIT_PAYLOAD";

    // PAT
    public static final String PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT_PAYLOAD = "PERFORMANCE_ACCOUNT_TEMPLATE_DATA_UPLOAD_SUBMIT_PAYLOAD";
}
