import { PerformanceAccountTemplateProcessingSubmittedRequestActionPayload } from 'cca-api';

export type PATUploadedActionPayload = PerformanceAccountTemplateProcessingSubmittedRequestActionPayload;
