import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'cca-api';

export const cancelTaskActionsMap: Record<
  RequestTaskDTO['type'],
  RequestTaskActionProcessDTO['requestTaskActionType']
> = {
  UNDERLYING_AGREEMENT_APPLICATION_SUBMIT: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_APPLICATION_REVIEW: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  ADMIN_TERMINATION_APPLICATION_SUBMIT: 'ADMIN_TERMINATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_SUBMIT: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_SUBMIT: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_ACTIVATION: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION:
    'CCA3_EXISTING_FACILITIES_MIGRATION_ACCOUNT_PROCESSING_ACTIVATION_CANCEL_APPLICATION',
  PRE_AUDIT_REVIEW_SUBMIT: 'FACILITY_AUDIT_CANCEL_APPLICATION',
  AUDIT_DETAILS_CORRECTIVE_ACTIONS_SUBMIT: 'FACILITY_AUDIT_CANCEL_APPLICATION',
  AUDIT_TRACK_CORRECTIVE_ACTIONS: 'FACILITY_AUDIT_CANCEL_APPLICATION',
  NON_COMPLIANCE_DETAILS_SUBMIT: 'NON_COMPLIANCE_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_REGULATOR_LED_ACTIVATION: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
};
