import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'cca-api';

export const cancelTaskActionsMap: Record<
  RequestTaskDTO['type'],
  RequestTaskActionProcessDTO['requestTaskActionType']
> = {
  UNDERLYING_AGREEMENT_APPLICATION_SUBMIT: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_APPLICATION_REVIEW: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_APPLICATION_ACTIVATION: 'UNDERLYING_AGREEMENT_CANCEL_APPLICATION',
  ADMIN_TERMINATION_APPLICATION_SUBMIT: 'ADMIN_TERMINATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_SUBMIT: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_APPLICATION_REVIEW: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
  UNDERLYING_AGREEMENT_VARIATION_ACTIVATION: 'UNDERLYING_AGREEMENT_VARIATION_CANCEL_APPLICATION',
};
