package uk.gov.cca.api.notification.template.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;
import uk.gov.cca.api.notification.template.config.DocumentGeneratorProperties;
import uk.gov.cca.api.notification.template.config.RestEndPointEnum;
import uk.gov.cca.api.notification.template.domain.dto.DocumentParameters;
import uk.gov.cca.api.notification.template.service.DocumentGeneratorRemoteClientService;

import java.util.HashMap;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class DocumentGeneratorRemoteClientServiceTest {

	@InjectMocks
    private DocumentGeneratorRemoteClientService cut;

    @Mock
    private DocumentGeneratorProperties properties;

    @Mock
    private RestTemplate restTemplate;
    
    @Test
    void generateDocument() throws Exception {
    	byte[] source = "some bytes".getBytes();
    	String outputFilename = "targetFile.pdf";
    	String baseUrl = "generatorServiceUrl";
    	
    	final HttpHeaders httpHeaders = new HttpHeaders();
    	httpHeaders.setContentType(MediaType.MULTIPART_FORM_DATA);
    	
    	final MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
		body.add("file", new ByteArrayResource(source) {
	        @Override
	        public String getFilename() {
	            return "source";
	        }
	    });
		body.add("parameters", DocumentParameters.builder().outputFilename(outputFilename).build());
    	
    	byte[] resultExpected = "some generated bytes".getBytes();

        when(properties.getUrl()).thenReturn(baseUrl);
        when(restTemplate.exchange(baseUrl + RestEndPointEnum.GENERATE.getEndPoint(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {}, new HashMap<>()))
                .thenReturn(new ResponseEntity<>(resultExpected, HttpStatus.OK));

        byte[] resultActual = cut.generateDocument(source, outputFilename);
        
        assertThat(resultActual).isEqualTo(resultExpected);

        verify(properties, times(1)).getUrl();
        verify(restTemplate, times(1)).exchange(baseUrl + RestEndPointEnum.GENERATE.getEndPoint(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {}, new HashMap<>());
    }
}
