export const mockSectorAccountsPerformanceReport = {
  performanceDataReportItems: [
    {
      accountId: 1,
      targetUnitAccountBusinessId: 'ADS-T0003',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 2,
      performanceOutcome: 'BUY_OUT_REQUIRED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 2,
      targetUnitAccountBusinessId: 'ADS-T0004',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 3,
      performanceOutcome: 'SURPLUS_USED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 3,
      targetUnitAccountBusinessId: 'ADS-T0005',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 1,
      performanceOutcome: 'SURPLUS_USED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 4,
      targetUnitAccountBusinessId: 'ADS-T0006',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-07-05',
      reportVersion: 2,
      performanceOutcome: 'BUY_OUT_REQUIRED',
      submissionType: 'SECONDARY',
    },
    {
      accountId: 5,
      targetUnitAccountBusinessId: 'ADS-T0007',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 1,
      performanceOutcome: 'SURPLUS_USED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 6,
      targetUnitAccountBusinessId: 'ADS-T0008',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 1,
      performanceOutcome: 'BUY_OUT_REQUIRED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 7,
      targetUnitAccountBusinessId: 'ADS-T0009',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 1,
      performanceOutcome: 'BUY_OUT_REQUIRED',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 8,
      targetUnitAccountBusinessId: 'ADS-T0010',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 0,
      performanceOutcome: 'OUTSTANDING',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 9,
      targetUnitAccountBusinessId: 'ADS-T0011',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 0,
      performanceOutcome: 'OUTSTANDING',
      submissionType: 'PRIMARY',
    },
    {
      accountId: 10,
      targetUnitAccountBusinessId: 'ADS-T0012',
      operatorName: 'Lorem Ipsum',
      submissionDate: '2025-04-25',
      reportVersion: 1,
      performanceOutcome: 'BUY_OUT_REQUIRED',
      submissionType: 'PRIMARY',
    },
  ],
  total: 10,
};
