/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { TargetPeriodBuyOutCostUpdateDTO } from '../model/targetPeriodBuyOutCostUpdateDTO';
import { TargetPeriodBuyOutDetailsDTO } from '../model/targetPeriodBuyOutDetailsDTO';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class BuyOutAndSurplusCostInfoService {
  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Retrieves the buy-out cost for each target period in the specified scheme
   * @param schemeVersion The scheme version
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getBuyOutCosts(schemeVersion: 'CCA_2' | 'CCA_3'): Observable<TargetPeriodBuyOutDetailsDTO[]>;
  public getBuyOutCosts(
    schemeVersion: 'CCA_2' | 'CCA_3',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<TargetPeriodBuyOutDetailsDTO[]>>;
  public getBuyOutCosts(
    schemeVersion: 'CCA_2' | 'CCA_3',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<TargetPeriodBuyOutDetailsDTO[]>>;
  public getBuyOutCosts(
    schemeVersion: 'CCA_2' | 'CCA_3',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<TargetPeriodBuyOutDetailsDTO[]>;
  public getBuyOutCosts(
    schemeVersion: 'CCA_2' | 'CCA_3',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (schemeVersion === null || schemeVersion === undefined) {
      throw new Error('Required parameter schemeVersion was null or undefined when calling getBuyOutCosts.');
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (schemeVersion !== undefined && schemeVersion !== null) {
      queryParameters = this.addToHttpParams(queryParameters, schemeVersion as any, 'schemeVersion');
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.get<TargetPeriodBuyOutDetailsDTO[]>(
      `${this.configuration.basePath}/v1.0/buy-out-surplus/cost`,
      {
        params: queryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Updates the buy-out cost for the specified target period
   * @param tp
   * @param targetPeriodBuyOutCostUpdateDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateBuyOutCost(
    tp: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    targetPeriodBuyOutCostUpdateDTO: TargetPeriodBuyOutCostUpdateDTO,
  ): Observable<any>;
  public updateBuyOutCost(
    tp: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    targetPeriodBuyOutCostUpdateDTO: TargetPeriodBuyOutCostUpdateDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<any>>;
  public updateBuyOutCost(
    tp: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    targetPeriodBuyOutCostUpdateDTO: TargetPeriodBuyOutCostUpdateDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<any>>;
  public updateBuyOutCost(
    tp: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    targetPeriodBuyOutCostUpdateDTO: TargetPeriodBuyOutCostUpdateDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any>;
  public updateBuyOutCost(
    tp: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    targetPeriodBuyOutCostUpdateDTO: TargetPeriodBuyOutCostUpdateDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (tp === null || tp === undefined) {
      throw new Error('Required parameter tp was null or undefined when calling updateBuyOutCost.');
    }
    if (targetPeriodBuyOutCostUpdateDTO === null || targetPeriodBuyOutCostUpdateDTO === undefined) {
      throw new Error(
        'Required parameter targetPeriodBuyOutCostUpdateDTO was null or undefined when calling updateBuyOutCost.',
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.patch<any>(
      `${this.configuration.basePath}/v1.0/buy-out-surplus/cost/${encodeURIComponent(String(tp))}`,
      targetPeriodBuyOutCostUpdateDTO,
      {
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
