/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { BuyOutSurplusTransactionUpdateAmountDTO } from '../model/buyOutSurplusTransactionUpdateAmountDTO';
import { BuyOutSurplusTransactionUpdatePaymentStatusDTO } from '../model/buyOutSurplusTransactionUpdatePaymentStatusDTO';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class BuyOutSurplusTransactionUpdateControllerService {
  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Updates the transaction buy out or refund amount and transaction history
   * @param id The transaction id
   * @param buyOutSurplusTransactionUpdateAmountDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateBuyOutSurplusTransactionAmount(
    id: number,
    buyOutSurplusTransactionUpdateAmountDTO: BuyOutSurplusTransactionUpdateAmountDTO,
  ): Observable<any>;
  public updateBuyOutSurplusTransactionAmount(
    id: number,
    buyOutSurplusTransactionUpdateAmountDTO: BuyOutSurplusTransactionUpdateAmountDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<any>>;
  public updateBuyOutSurplusTransactionAmount(
    id: number,
    buyOutSurplusTransactionUpdateAmountDTO: BuyOutSurplusTransactionUpdateAmountDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<any>>;
  public updateBuyOutSurplusTransactionAmount(
    id: number,
    buyOutSurplusTransactionUpdateAmountDTO: BuyOutSurplusTransactionUpdateAmountDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any>;
  public updateBuyOutSurplusTransactionAmount(
    id: number,
    buyOutSurplusTransactionUpdateAmountDTO: BuyOutSurplusTransactionUpdateAmountDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateBuyOutSurplusTransactionAmount.');
    }
    if (buyOutSurplusTransactionUpdateAmountDTO === null || buyOutSurplusTransactionUpdateAmountDTO === undefined) {
      throw new Error(
        'Required parameter buyOutSurplusTransactionUpdateAmountDTO was null or undefined when calling updateBuyOutSurplusTransactionAmount.',
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.post<any>(
      `${this.configuration.basePath}/v1.0/buy-out-surplus/transactions/${encodeURIComponent(String(id))}/update/amount`,
      buyOutSurplusTransactionUpdateAmountDTO,
      {
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Updates the transaction payment status and transaction history
   * @param id The transaction id
   * @param buyOutSurplusTransactionUpdatePaymentStatusDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateBuyOutSurplusTransactionPaymentStatus(
    id: number,
    buyOutSurplusTransactionUpdatePaymentStatusDTO: BuyOutSurplusTransactionUpdatePaymentStatusDTO,
  ): Observable<any>;
  public updateBuyOutSurplusTransactionPaymentStatus(
    id: number,
    buyOutSurplusTransactionUpdatePaymentStatusDTO: BuyOutSurplusTransactionUpdatePaymentStatusDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<any>>;
  public updateBuyOutSurplusTransactionPaymentStatus(
    id: number,
    buyOutSurplusTransactionUpdatePaymentStatusDTO: BuyOutSurplusTransactionUpdatePaymentStatusDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<any>>;
  public updateBuyOutSurplusTransactionPaymentStatus(
    id: number,
    buyOutSurplusTransactionUpdatePaymentStatusDTO: BuyOutSurplusTransactionUpdatePaymentStatusDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any>;
  public updateBuyOutSurplusTransactionPaymentStatus(
    id: number,
    buyOutSurplusTransactionUpdatePaymentStatusDTO: BuyOutSurplusTransactionUpdatePaymentStatusDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling updateBuyOutSurplusTransactionPaymentStatus.',
      );
    }
    if (
      buyOutSurplusTransactionUpdatePaymentStatusDTO === null ||
      buyOutSurplusTransactionUpdatePaymentStatusDTO === undefined
    ) {
      throw new Error(
        'Required parameter buyOutSurplusTransactionUpdatePaymentStatusDTO was null or undefined when calling updateBuyOutSurplusTransactionPaymentStatus.',
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.post<any>(
      `${this.configuration.basePath}/v1.0/buy-out-surplus/transactions/${encodeURIComponent(String(id))}/update/payment-status`,
      buyOutSurplusTransactionUpdatePaymentStatusDTO,
      {
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
