/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  HttpClient,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParameterCodec,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Service } from '@angular/core';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';
import { CustomHttpParameterCodec } from '../encoder';
// All model imports come from the models barrel file
import { RequestCreateActionProcessDTO, RequestCreateActionProcessResponseDTO } from '../model/models';
import { BASE_PATH } from '../variables';

@Service()
export class CcaRequestsService {
  protected httpClient = inject(HttpClient);

  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor() {
    let basePath: string | string[] | null = inject(BASE_PATH, { optional: true });
    const configuration = inject(Configuration, { optional: true });

    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
      if (firstBasePath != undefined) {
        basePath = firstBasePath;
      }

      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Processes a cca request create action
   * @param sectorAssociationId The sector association id
   * @param requestCreateActionProcessDTO
   * @param accountId The account id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public processCcaRequestCreateAction(
    sectorAssociationId: number,
    requestCreateActionProcessDTO: RequestCreateActionProcessDTO,
    accountId?: number,
  ): Observable<RequestCreateActionProcessResponseDTO>;
  public processCcaRequestCreateAction(
    sectorAssociationId: number,
    requestCreateActionProcessDTO: RequestCreateActionProcessDTO,
    accountId: number,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<RequestCreateActionProcessResponseDTO>>;
  public processCcaRequestCreateAction(
    sectorAssociationId: number,
    requestCreateActionProcessDTO: RequestCreateActionProcessDTO,
    accountId: number,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<RequestCreateActionProcessResponseDTO>>;
  public processCcaRequestCreateAction(
    sectorAssociationId: number,
    requestCreateActionProcessDTO: RequestCreateActionProcessDTO,
    accountId: number,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<RequestCreateActionProcessResponseDTO>;
  public processCcaRequestCreateAction(
    sectorAssociationId: number,
    requestCreateActionProcessDTO: RequestCreateActionProcessDTO,
    accountId?: number,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (sectorAssociationId === null || sectorAssociationId === undefined) {
      throw new Error(
        'Required parameter sectorAssociationId was null or undefined when calling processCcaRequestCreateAction.',
      );
    }
    if (requestCreateActionProcessDTO === null || requestCreateActionProcessDTO === undefined) {
      throw new Error(
        'Required parameter requestCreateActionProcessDTO was null or undefined when calling processCcaRequestCreateAction.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (sectorAssociationId !== undefined && sectorAssociationId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        sectorAssociationId as any,
        'sectorAssociationId',
      );
    }
    if (accountId !== undefined && accountId !== null) {
      localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, accountId as any, 'accountId');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/cca-requests`;
    return this.httpClient.request<RequestCreateActionProcessResponseDTO>(
      'post',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: requestCreateActionProcessDTO,
        params: localVarQueryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }
}
