/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  HttpClient,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParameterCodec,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Service } from '@angular/core';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';
import { CustomHttpParameterCodec } from '../encoder';
// All model imports come from the models barrel file
import {
  AccountPerformanceAccountTemplateDataReportDetailsDTO,
  AccountPerformanceAccountTemplateDataReportInfoDTO,
  FileToken,
} from '../model/models';
import { BASE_PATH } from '../variables';

@Service()
export class TargetPeriodPerformanceAccountTemplateDataReportOfTheAccountService {
  protected httpClient = inject(HttpClient);

  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor() {
    let basePath: string | string[] | null = inject(BASE_PATH, { optional: true });
    const configuration = inject(Configuration, { optional: true });

    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
      if (firstBasePath != undefined) {
        basePath = firstBasePath;
      }

      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Retrieves the attachment token for the account and the target period
   * @param accountId The account id
   * @param targetPeriodType The target period type
   * @param fileAttachmentUuid The attachment uuid
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    fileAttachmentUuid: string,
  ): Observable<FileToken>;
  public generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    fileAttachmentUuid: string,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<FileToken>>;
  public generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    fileAttachmentUuid: string,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<FileToken>>;
  public generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    fileAttachmentUuid: string,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<FileToken>;
  public generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    fileAttachmentUuid: string,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken.',
      );
    }
    if (fileAttachmentUuid === null || fileAttachmentUuid === undefined) {
      throw new Error(
        'Required parameter fileAttachmentUuid was null or undefined when calling generateGetAccountPerformanceAccountTemplateDataReportAttachmentToken.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        targetPeriodType as any,
        'targetPeriodType',
      );
    }
    if (fileAttachmentUuid !== undefined && fileAttachmentUuid !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        fileAttachmentUuid as any,
        'fileAttachmentUuid',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/target-unit-accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-account-template-data-report/attachment-token`;
    return this.httpClient.request<FileToken>('get', `${this.configuration.basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: responseType_ as any,
      withCredentials: this.configuration.withCredentials,
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress,
    });
  }

  /**
   * Retrieves the performance account template report details
   * @param accountId The account id
   * @param targetPeriodType The target period business id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountPerformanceAccountTemplateDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
  ): Observable<AccountPerformanceAccountTemplateDataReportDetailsDTO>;
  public getAccountPerformanceAccountTemplateDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<AccountPerformanceAccountTemplateDataReportDetailsDTO>>;
  public getAccountPerformanceAccountTemplateDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<AccountPerformanceAccountTemplateDataReportDetailsDTO>>;
  public getAccountPerformanceAccountTemplateDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<AccountPerformanceAccountTemplateDataReportDetailsDTO>;
  public getAccountPerformanceAccountTemplateDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getAccountPerformanceAccountTemplateDataReportDetails.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling getAccountPerformanceAccountTemplateDataReportDetails.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        targetPeriodType as any,
        'targetPeriodType',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/target-unit-accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-account-template-data-report/details`;
    return this.httpClient.request<AccountPerformanceAccountTemplateDataReportDetailsDTO>(
      'get',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Retrieves the performance account template report info if exist
   * @param accountId The account id
   * @param targetPeriodType The target period business id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountPerformanceAccountTemplateDataReportInfo(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
  ): Observable<AccountPerformanceAccountTemplateDataReportInfoDTO>;
  public getAccountPerformanceAccountTemplateDataReportInfo(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<AccountPerformanceAccountTemplateDataReportInfoDTO>>;
  public getAccountPerformanceAccountTemplateDataReportInfo(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<AccountPerformanceAccountTemplateDataReportInfoDTO>>;
  public getAccountPerformanceAccountTemplateDataReportInfo(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<AccountPerformanceAccountTemplateDataReportInfoDTO>;
  public getAccountPerformanceAccountTemplateDataReportInfo(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getAccountPerformanceAccountTemplateDataReportInfo.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling getAccountPerformanceAccountTemplateDataReportInfo.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        targetPeriodType as any,
        'targetPeriodType',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/target-unit-accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-account-template-data-report/info`;
    return this.httpClient.request<AccountPerformanceAccountTemplateDataReportInfoDTO>(
      'get',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }
}
