/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  HttpClient,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParameterCodec,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Service } from '@angular/core';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';
import { CustomHttpParameterCodec } from '../encoder';
// All model imports come from the models barrel file
import {
  FacilityPerformanceDataReportDetailsDTO,
  FacilityPerformanceDataStatusInfoDTO,
  FacilityPerformanceDataUpdateLockDTO,
  FacilityPerformanceDataUpdateVariationIndicatorDTO,
} from '../model/models';
import { BASE_PATH } from '../variables';

@Service()
export class TargetPeriodPerformanceDataReportOfTheFacilityService {
  protected httpClient = inject(HttpClient);

  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor() {
    let basePath: string | string[] | null = inject(BASE_PATH, { optional: true });
    const configuration = inject(Configuration, { optional: true });

    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
      if (firstBasePath != undefined) {
        basePath = firstBasePath;
      }

      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Retrieves the latest performance data for the facility and the target period year.
   * @param facilityId The facility id
   * @param targetPeriodYear The target period year
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFacilityPerformanceDataReportDetails(
    facilityId: number,
    targetPeriodYear: string,
  ): Observable<FacilityPerformanceDataReportDetailsDTO>;
  public getFacilityPerformanceDataReportDetails(
    facilityId: number,
    targetPeriodYear: string,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<FacilityPerformanceDataReportDetailsDTO>>;
  public getFacilityPerformanceDataReportDetails(
    facilityId: number,
    targetPeriodYear: string,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<FacilityPerformanceDataReportDetailsDTO>>;
  public getFacilityPerformanceDataReportDetails(
    facilityId: number,
    targetPeriodYear: string,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<FacilityPerformanceDataReportDetailsDTO>;
  public getFacilityPerformanceDataReportDetails(
    facilityId: number,
    targetPeriodYear: string,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (facilityId === null || facilityId === undefined) {
      throw new Error(
        'Required parameter facilityId was null or undefined when calling getFacilityPerformanceDataReportDetails.',
      );
    }
    if (targetPeriodYear === null || targetPeriodYear === undefined) {
      throw new Error(
        'Required parameter targetPeriodYear was null or undefined when calling getFacilityPerformanceDataReportDetails.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodYear !== undefined && targetPeriodYear !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        targetPeriodYear as any,
        'targetPeriodYear',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/facilities/${this.configuration.encodeParam({ name: 'facilityId', value: facilityId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-data-report/details`;
    return this.httpClient.request<FacilityPerformanceDataReportDetailsDTO>(
      'get',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Retrieves the facility performance data status info
   * @param facilityId The facility id
   * @param targetPeriodType The target period business id
   * @param reportType The performance data report type
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFacilityPerformanceDataStatus(
    facilityId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    reportType: 'INTERIM' | 'FINAL',
  ): Observable<FacilityPerformanceDataStatusInfoDTO[]>;
  public getFacilityPerformanceDataStatus(
    facilityId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    reportType: 'INTERIM' | 'FINAL',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<FacilityPerformanceDataStatusInfoDTO[]>>;
  public getFacilityPerformanceDataStatus(
    facilityId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    reportType: 'INTERIM' | 'FINAL',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<FacilityPerformanceDataStatusInfoDTO[]>>;
  public getFacilityPerformanceDataStatus(
    facilityId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    reportType: 'INTERIM' | 'FINAL',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<FacilityPerformanceDataStatusInfoDTO[]>;
  public getFacilityPerformanceDataStatus(
    facilityId: number,
    targetPeriodType: 'TP5' | 'TP6' | 'TP7' | 'TP8' | 'TP9',
    reportType: 'INTERIM' | 'FINAL',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (facilityId === null || facilityId === undefined) {
      throw new Error(
        'Required parameter facilityId was null or undefined when calling getFacilityPerformanceDataStatus.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling getFacilityPerformanceDataStatus.',
      );
    }
    if (reportType === null || reportType === undefined) {
      throw new Error(
        'Required parameter reportType was null or undefined when calling getFacilityPerformanceDataStatus.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        targetPeriodType as any,
        'targetPeriodType',
      );
    }
    if (reportType !== undefined && reportType !== null) {
      localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, reportType as any, 'reportType');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/facilities/${this.configuration.encodeParam({ name: 'facilityId', value: facilityId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-data-report/status`;
    return this.httpClient.request<FacilityPerformanceDataStatusInfoDTO[]>(
      'get',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Locks/unlocks the facility for reporting performance data for the specified target period year
   * @param facilityId The facility id
   * @param facilityPerformanceDataUpdateLockDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateFacilityPerformanceDataLock(
    facilityId: number,
    facilityPerformanceDataUpdateLockDTO: FacilityPerformanceDataUpdateLockDTO,
  ): Observable<FacilityPerformanceDataUpdateLockDTO>;
  public updateFacilityPerformanceDataLock(
    facilityId: number,
    facilityPerformanceDataUpdateLockDTO: FacilityPerformanceDataUpdateLockDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<FacilityPerformanceDataUpdateLockDTO>>;
  public updateFacilityPerformanceDataLock(
    facilityId: number,
    facilityPerformanceDataUpdateLockDTO: FacilityPerformanceDataUpdateLockDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<FacilityPerformanceDataUpdateLockDTO>>;
  public updateFacilityPerformanceDataLock(
    facilityId: number,
    facilityPerformanceDataUpdateLockDTO: FacilityPerformanceDataUpdateLockDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<FacilityPerformanceDataUpdateLockDTO>;
  public updateFacilityPerformanceDataLock(
    facilityId: number,
    facilityPerformanceDataUpdateLockDTO: FacilityPerformanceDataUpdateLockDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (facilityId === null || facilityId === undefined) {
      throw new Error(
        'Required parameter facilityId was null or undefined when calling updateFacilityPerformanceDataLock.',
      );
    }
    if (facilityPerformanceDataUpdateLockDTO === null || facilityPerformanceDataUpdateLockDTO === undefined) {
      throw new Error(
        'Required parameter facilityPerformanceDataUpdateLockDTO was null or undefined when calling updateFacilityPerformanceDataLock.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/facilities/${this.configuration.encodeParam({ name: 'facilityId', value: facilityId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-data-report/lock`;
    return this.httpClient.request<FacilityPerformanceDataUpdateLockDTO>(
      'put',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: facilityPerformanceDataUpdateLockDTO,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Sets the variation indicator for the facility performance data for the specified target period year
   * @param facilityId The facility id
   * @param facilityPerformanceDataUpdateVariationIndicatorDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateFacilityPerformanceDataVariationIndicator(
    facilityId: number,
    facilityPerformanceDataUpdateVariationIndicatorDTO: FacilityPerformanceDataUpdateVariationIndicatorDTO,
  ): Observable<FacilityPerformanceDataUpdateVariationIndicatorDTO>;
  public updateFacilityPerformanceDataVariationIndicator(
    facilityId: number,
    facilityPerformanceDataUpdateVariationIndicatorDTO: FacilityPerformanceDataUpdateVariationIndicatorDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<FacilityPerformanceDataUpdateVariationIndicatorDTO>>;
  public updateFacilityPerformanceDataVariationIndicator(
    facilityId: number,
    facilityPerformanceDataUpdateVariationIndicatorDTO: FacilityPerformanceDataUpdateVariationIndicatorDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<FacilityPerformanceDataUpdateVariationIndicatorDTO>>;
  public updateFacilityPerformanceDataVariationIndicator(
    facilityId: number,
    facilityPerformanceDataUpdateVariationIndicatorDTO: FacilityPerformanceDataUpdateVariationIndicatorDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<FacilityPerformanceDataUpdateVariationIndicatorDTO>;
  public updateFacilityPerformanceDataVariationIndicator(
    facilityId: number,
    facilityPerformanceDataUpdateVariationIndicatorDTO: FacilityPerformanceDataUpdateVariationIndicatorDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (facilityId === null || facilityId === undefined) {
      throw new Error(
        'Required parameter facilityId was null or undefined when calling updateFacilityPerformanceDataVariationIndicator.',
      );
    }
    if (
      facilityPerformanceDataUpdateVariationIndicatorDTO === null ||
      facilityPerformanceDataUpdateVariationIndicatorDTO === undefined
    ) {
      throw new Error(
        'Required parameter facilityPerformanceDataUpdateVariationIndicatorDTO was null or undefined when calling updateFacilityPerformanceDataVariationIndicator.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    const localVarCredential: string | undefined = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/v1.0/facilities/${this.configuration.encodeParam({ name: 'facilityId', value: facilityId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/performance-data-report/variation-indicator`;
    return this.httpClient.request<FacilityPerformanceDataUpdateVariationIndicatorDTO>(
      'put',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: facilityPerformanceDataUpdateVariationIndicatorDTO,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }
}
