/**
 * API Documentation
 * API Documentation
 *
 * The version of the OpenAPI document: uk-cca-app-api 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { AccountPerformanceDataReportDetailsDTO } from '../model/accountPerformanceDataReportDetailsDTO';
import { AccountPerformanceDataStatusInfoDTO } from '../model/accountPerformanceDataStatusInfoDTO';
import { AccountPerformanceDataUpdateLockDTO } from '../model/accountPerformanceDataUpdateLockDTO';
import { FileToken } from '../model/fileToken';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class TargetPeriodPerformanceDataReportOfTheAccountService {
  protected basePath = '/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Retrieves the latest performance data file for the account and the target period.
   * @param accountId The account id
   * @param targetPeriodType The target period business id
   * @param fileAttachmentUuid The attachment uuid
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public generateGetAccountPerformanceDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    fileAttachmentUuid: string,
  ): Observable<FileToken>;
  public generateGetAccountPerformanceDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    fileAttachmentUuid: string,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<FileToken>>;
  public generateGetAccountPerformanceDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    fileAttachmentUuid: string,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<FileToken>>;
  public generateGetAccountPerformanceDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    fileAttachmentUuid: string,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<FileToken>;
  public generateGetAccountPerformanceDataReportAttachmentToken(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    fileAttachmentUuid: string,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling generateGetAccountPerformanceDataReportAttachmentToken.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling generateGetAccountPerformanceDataReportAttachmentToken.',
      );
    }
    if (fileAttachmentUuid === null || fileAttachmentUuid === undefined) {
      throw new Error(
        'Required parameter fileAttachmentUuid was null or undefined when calling generateGetAccountPerformanceDataReportAttachmentToken.',
      );
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      queryParameters = this.addToHttpParams(queryParameters, targetPeriodType as any, 'targetPeriodType');
    }
    if (fileAttachmentUuid !== undefined && fileAttachmentUuid !== null) {
      queryParameters = this.addToHttpParams(queryParameters, fileAttachmentUuid as any, 'fileAttachmentUuid');
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.get<FileToken>(
      `${this.configuration.basePath}/v1.0/target-unit-accounts/${encodeURIComponent(String(accountId))}/performance-data-report/attachment`,
      {
        params: queryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Retrieves the latest performance data for the account and the target period.
   * @param accountId The account id
   * @param targetPeriodType The target period business id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountPerformanceDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
  ): Observable<AccountPerformanceDataReportDetailsDTO>;
  public getAccountPerformanceDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<AccountPerformanceDataReportDetailsDTO>>;
  public getAccountPerformanceDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<AccountPerformanceDataReportDetailsDTO>>;
  public getAccountPerformanceDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<AccountPerformanceDataReportDetailsDTO>;
  public getAccountPerformanceDataReportDetails(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getAccountPerformanceDataReportDetails.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling getAccountPerformanceDataReportDetails.',
      );
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      queryParameters = this.addToHttpParams(queryParameters, targetPeriodType as any, 'targetPeriodType');
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.get<AccountPerformanceDataReportDetailsDTO>(
      `${this.configuration.basePath}/v1.0/target-unit-accounts/${encodeURIComponent(String(accountId))}/performance-data-report/details`,
      {
        params: queryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Retrieves the account performance data status info
   * @param accountId The account id
   * @param targetPeriodType The target period business id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountPerformanceDataStatus(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
  ): Observable<AccountPerformanceDataStatusInfoDTO>;
  public getAccountPerformanceDataStatus(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<AccountPerformanceDataStatusInfoDTO>>;
  public getAccountPerformanceDataStatus(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<AccountPerformanceDataStatusInfoDTO>>;
  public getAccountPerformanceDataStatus(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<AccountPerformanceDataStatusInfoDTO>;
  public getAccountPerformanceDataStatus(
    accountId: number,
    targetPeriodType: 'TP5' | 'TP6',
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getAccountPerformanceDataStatus.',
      );
    }
    if (targetPeriodType === null || targetPeriodType === undefined) {
      throw new Error(
        'Required parameter targetPeriodType was null or undefined when calling getAccountPerformanceDataStatus.',
      );
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (targetPeriodType !== undefined && targetPeriodType !== null) {
      queryParameters = this.addToHttpParams(queryParameters, targetPeriodType as any, 'targetPeriodType');
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.get<AccountPerformanceDataStatusInfoDTO>(
      `${this.configuration.basePath}/v1.0/target-unit-accounts/${encodeURIComponent(String(accountId))}/performance-data-report/status`,
      {
        params: queryParameters,
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Locks/unlocks the account for reporting performance data for the specified target period
   * @param accountId The account id
   * @param accountPerformanceDataUpdateLockDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateAccountPerformanceDataLock(
    accountId: number,
    accountPerformanceDataUpdateLockDTO: AccountPerformanceDataUpdateLockDTO,
  ): Observable<AccountPerformanceDataUpdateLockDTO>;
  public updateAccountPerformanceDataLock(
    accountId: number,
    accountPerformanceDataUpdateLockDTO: AccountPerformanceDataUpdateLockDTO,
    observe: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpResponse<AccountPerformanceDataUpdateLockDTO>>;
  public updateAccountPerformanceDataLock(
    accountId: number,
    accountPerformanceDataUpdateLockDTO: AccountPerformanceDataUpdateLockDTO,
    observe: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<HttpEvent<AccountPerformanceDataUpdateLockDTO>>;
  public updateAccountPerformanceDataLock(
    accountId: number,
    accountPerformanceDataUpdateLockDTO: AccountPerformanceDataUpdateLockDTO,
    observe: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<AccountPerformanceDataUpdateLockDTO>;
  public updateAccountPerformanceDataLock(
    accountId: number,
    accountPerformanceDataUpdateLockDTO: AccountPerformanceDataUpdateLockDTO,
    observe: any = 'body',
    reportProgress = false,
    options?: { httpHeaderAccept?: 'application/json' },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling updateAccountPerformanceDataLock.',
      );
    }
    if (accountPerformanceDataUpdateLockDTO === null || accountPerformanceDataUpdateLockDTO === undefined) {
      throw new Error(
        'Required parameter accountPerformanceDataUpdateLockDTO was null or undefined when calling updateAccountPerformanceDataLock.',
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    const credential = this.configuration.lookupCredential('bearerAuth');
    if (credential) {
      headers = headers.set('Authorization', 'Bearer ' + credential);
    }

    let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (httpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' = 'json';
    if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
      responseType_ = 'text';
    }

    return this.httpClient.put<AccountPerformanceDataUpdateLockDTO>(
      `${this.configuration.basePath}/v1.0/target-unit-accounts/${encodeURIComponent(String(accountId))}/performance-data-report/lock`,
      accountPerformanceDataUpdateLockDTO,
      {
        responseType: responseType_ as any,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
