package uk.gov.cca.api.migration.underlyingagreement.legacyattachment;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum LegacyFileAttachmentType {

    TARGET_PERIOD_DETAILS_TARGET_CALCULATOR_FILE("Target calc"),
    TARGET_PERIOD_DETAILS_CONVERSION_EVIDENCE("Throughput conversion"),
    TARGET_PERIOD_DETAILS_GREENFIELD_EVIDENCE("Greenfield evidence"),
    MANAGE_FACILITIES_MANUFACTURING_PROCESS_DESCRIPTION("MPD"),
    MANAGE_FACILITIES_PROCESS_FLOW_MAPS("PFM"),
    MANAGE_FACILITIES_ANNOTATED_SITE_PLANS("ASP"),
    MANAGE_FACILITIES_ELIGIBLE_PROCESS_DESCRIPTION("EPD"),
    MANAGE_FACILITIES_DIRECTLY_ASSOCIATED_ACTIVITIES_DESCRIPTION("DAA"), 
    MANAGE_FACILITIES_PERMIT_FILE("EPR"), 
    MANAGE_FACILITIES_EVIDENCE("70_30"),
    AUTHORISATION_AND_ADDITIONAL_EVIDENCE_AUTHORISATION("Authorisation"),
    AUTHORISATION_AND_ADDITIONAL_EVIDENCE_ADDITIONAL_EVIDENCE("Other");

    private final String index;
}