import { SectorFacilityPerformanceDataReportListDTO } from 'cca-api';

export const mockSectorFacilitiesPerformanceReport: SectorFacilityPerformanceDataReportListDTO = {
  performanceDataReportItems: [
    {
      facilityId: 40,
      facilityBusinessId: 'ADS-F00040',
      siteName: 'Facility 40',
      accountId: 1,
      submissionDate: '2027-04-25',
      reportVersion: 2,
      reportStatus: 'TARGET_NOT_MET',
      submissionType: 'PRIMARY',
      locked: false,
      variationIndicator: true,
      atLeastSeventyPercentEnergyUsed: true,
      surplusGained: '0',
      actualEnergyCarbon: '1200',
      targetEnergyCarbon: '1000',
      energyCarbonDifference: '200',
      targetCo2Emissions: '900',
      actualCo2Emissions: '950',
      co2EmissionsDifference: '50',
      actualImprovement: '3',
      buyOutRequired: '150',
    },
    {
      facilityId: 41,
      facilityBusinessId: 'ADS-F00041',
      siteName: 'Facility 41',
      accountId: 1,
      submissionDate: '2027-04-25',
      reportVersion: 3,
      reportStatus: 'TARGET_MET',
      submissionType: 'PRIMARY',
      locked: true,
      variationIndicator: false,
      atLeastSeventyPercentEnergyUsed: true,
      surplusGained: '25',
      actualEnergyCarbon: '900',
      targetEnergyCarbon: '1000',
      energyCarbonDifference: '-100',
      targetCo2Emissions: '900',
      actualCo2Emissions: '800',
      co2EmissionsDifference: '-100',
      actualImprovement: '8',
      buyOutRequired: '0',
    },
    {
      facilityId: 42,
      facilityBusinessId: 'ADS-F00042',
      siteName: 'Facility 42',
      accountId: 2,
      reportVersion: 0,
      reportStatus: 'OUTSTANDING',
      locked: false,
      variationIndicator: false,
    },
  ],
  total: 3,
};
